httpclient-cache/src/test/java/org/apache/http/impl/client/cache/TestCacheEntryUpdater.java
Completed test case by adding second assertion
=> HTTPCLIENT-1690: Updated a test case

httpclient5/src/main/java/org/apache/hc/client5/http/HttpResponseException.java, httpclient5/src/test/java/org/apache/hc/client5/http/impl/classic/TestAbstractHttpClientResponseHandler.java
(cherry picked from commit 20dfff12c4dc3f73fe5d19b690c2eee033ed4125)
=> replace empty HttpResponseException.message with statusCode

httpclient5/src/main/java/org/apache/hc/client5/http/socket/PlainConnectionSocketFactory.java, httpclient5/src/main/java/org/apache/hc/client5/http/ssl/SSLConnectionSocketFactory.java
In order to allow users to run under a security manager that only grants
connect permission to the httpcore codebase the connect methods should
be executed in a doPriveledged block.
This is certainly not the only issue that users run into when they
install a SecurityManager with strict permissions but certainly the
most prominent and most likely one. Upstream components like the client
might also need to protect places accessing the proxy selector etc.
=> Execute Socket#connect under doPrivileged

httpclient/src/main/java/org/apache/http/client/config/RequestConfig.java
Cleaned up duplicate sentences and removed 'system default' from getSocketTimeout comment ([HTTPCLIENT-1765](https://issues.apache.org/jira/browse/HTTPCLIENT-1765)).
=> Modify RequestConfig Javadoc

httpclient/src/main/java/org/apache/http/impl/client/DefaultRedirectStrategy.java, httpclient/src/main/java/org/apache/http/impl/client/LaxRedirectStrategy.java
If this makes it in, I can provide another PR for 5.0.
=> Refactor DefaultRedirectStrategy for subclassing where I want to provide

httpclient/src/main/java/org/apache/http/impl/conn/PoolingHttpClientConnectionManager.java
because we're seeing the `totals.getAvailable()` , so  ` total available` seems better than `total kept alive` , the latter is a little bit confusing.
=> update text in pool stats description

httpclient5-win/src/main/java/org/apache/hc/client5/http/impl/win/WinHttpClients.java, httpclient5-win/src/main/java/org/apache/hc/client5/http/impl/win/WindowsNTLMSchemeFactory.java, httpclient5-win/src/main/java/org/apache/hc/client5/http/impl/win/WindowsNegotiateSchemeFactory.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/H2AsyncClientBuilder.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/HttpAsyncClientBuilder.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/auth/BasicSchemeFactory.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/auth/DigestSchemeFactory.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/auth/KerberosSchemeFactory.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/auth/NTLMSchemeFactory.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/auth/SPNegoSchemeFactory.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/HttpClientBuilder.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/ProxyClient.java, httpclient5/src/test/java/org/apache/hc/client5/http/impl/TestAuthenticationStrategy.java, httpclient5/src/test/java/org/apache/hc/client5/http/impl/auth/TestHttpAuthenticator.java
[HTTPCLIENT-2044] Don't create stateless/immutable factory objects.
=> Httpclient 2044 reuse immutables

httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/CloseableHttpAsyncClient.java
For JIRA ticket HTTPCLIENT-2057
Removed the unnecessary BasicFuture wrapping in CloseableHttpAsyncClient
=> Removed unnecessary BasicFuture wrapping

httpclient5/src/main/java/org/apache/hc/client5/http/impl/nio/PoolingAsyncClientConnectionManager.java
https://issues.apache.org/jira/browse/HTTPCLIENT-2097
=> HTTPCLIENT-2097: Fix PoolingAsyncClientConnectionManager boxed primitive reference equality

httpclient5/src/main/java/org/apache/hc/client5/http/impl/cookie/BasicExpiresHandler.java
=> BasicExpiresHandler is annotated as immutable but is not.

httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/H2AsyncClientBuilder.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/HttpAsyncClientBuilder.java, httpclient5/src/test/java/org/apache/hc/client5/http/impl/classic/TestHttpAsyncClientBuilder.java
=> Fix NPE when H2/Async client interceptors are added using first/last

httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/ResponseCachingPolicy.java, httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/WarningValue.java, httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/AbstractProtocolTest.java, httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestRequestProtocolCompliance.java, httpclient5-cache/src/test/java/org/apache/hc/client5/http/schedule/TestConcurrentCountMap.java, httpclient5-testing/src/test/java/org/apache/hc/client5/testing/async/AbstractHttpAsyncClientAuthentication.java, httpclient5-testing/src/test/java/org/apache/hc/client5/testing/fluent/TestFluent.java, httpclient5-testing/src/test/java/org/apache/hc/client5/testing/sync/TestClientAuthentication.java, httpclient5-testing/src/test/java/org/apache/hc/client5/testing/sync/TestRedirects.java, httpclient5-testing/src/test/java/org/apache/hc/client5/testing/sync/TestSPNegoScheme.java, httpclient5/src/main/java/org/apache/hc/client5/http/auth/AuthScope.java, httpclient5/src/main/java/org/apache/hc/client5/http/cookie/CookieOrigin.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/LoggingExceptionCallback.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/auth/NTLMEngineImpl.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/ManagedHttpClientConnectionFactory.java, httpclient5/src/main/java/org/apache/hc/client5/http/psl/PublicSuffixMatcherLoader.java, httpclient5/src/test/java/org/apache/hc/client5/http/entity/mime/TestMultipartForm.java, httpclient5/src/test/java/org/apache/hc/client5/http/entity/mime/TestMultipartMixed.java, httpclient5/src/test/java/org/apache/hc/client5/http/entity/mime/TestMultipartPartBuilder.java, httpclient5/src/test/java/org/apache/hc/client5/http/examples/ClientConfiguration.java, httpclient5/src/test/java/org/apache/hc/client5/http/impl/auth/TestNTLMEngineImpl.java, httpclient5/src/test/java/org/apache/hc/client5/http/impl/classic/TestFutureRequestExecutionService.java, httpclient5/src/test/java/org/apache/hc/client5/http/impl/cookie/TestRFC6265CookieSpec.java, httpclient5/src/test/java/org/apache/hc/client5/http/psl/TestPublicSuffixListParser.java, httpclient5/src/test/java/org/apache/hc/client5/http/ssl/TestDefaultHostnameVerifier.java, httpclient5/src/test/java/org/apache/hc/client5/http/utils/TestURIUtils.java
* Add final to variable
* Unnecessary semicolon
* Use Standard Charset object
* Unnecessary conversion to String
* Simplifiable conditional expression
* Replace 'Arrays.asList()' with Collections.singletonList
* Redundant local variable. Simplify
=> Minor Improvements:

httpclient5-cache/pom.xml, httpclient5-fluent/pom.xml, httpclient5-testing/pom.xml, httpclient5-win/pom.xml, httpclient5/pom.xml, pom.xml, src/site/resources/css/site.css, src/site/site.xml
these improvements are useful in master branch, whatever happens to current discussions on testing and eventually changing some structure
=> improve documentation format

pom.xml, src/site/site.xml
you can either put that as a branch to do tests, either directly in master given it's not a revolution
@michael-o
=> activate SCM publish to /httpcomponents-client-5.0.x/doc/

httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachedResponseSuitabilityChecker.java, httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachingExecBase.java, httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/RequestProtocolCompliance.java, httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/ResponseCachingPolicy.java, httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/WarningValue.java, httpclient5-testing/src/main/java/org/apache/hc/client5/testing/classic/EchoHandler.java, httpclient5/src/main/java/org/apache/hc/client5/http/auth/BasicUserPrincipal.java, httpclient5/src/main/java/org/apache/hc/client5/http/auth/NTCredentials.java, httpclient5/src/main/java/org/apache/hc/client5/http/auth/NTUserPrincipal.java, httpclient5/src/main/java/org/apache/hc/client5/http/auth/UsernamePasswordCredentials.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/auth/DigestScheme.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/cookie/BasicDomainHandler.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/cookie/BasicPathHandler.java, httpclient5/src/main/java/org/apache/hc/client5/http/psl/PublicSuffixMatcher.java, httpclient5/src/main/java/org/apache/hc/client5/http/ssl/DefaultHostnameVerifier.java
* Avoid duplicate code
* Simplify if else
* Inline variables
=> Minor Improvement:

httpclient5/src/main/java/org/apache/hc/client5/http/protocol/ResponseProcessCookies.java
Remove duplicated conditional statement in `ResponseProcessCookies.java`
=> Remove duplicated conditional statement in ResponseProcessCookies

httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachedHttpResponseGenerator.java, httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/ResponseCachingPolicy.java, httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/WarningValue.java, httpclient5/src/main/java/org/apache/hc/client5/http/HttpRequestRetryStrategy.java, httpclient5/src/main/java/org/apache/hc/client5/http/cookie/CookieAttributeHandler.java, httpclient5/src/main/java/org/apache/hc/client5/http/cookie/CookiePriorityComparator.java, httpclient5/src/main/java/org/apache/hc/client5/http/cookie/StandardCookieSpec.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/DefaultUserTokenHandler.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/H2AsyncClientBuilder.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/HttpAsyncClientBuilder.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/auth/DigestScheme.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/auth/HttpAuthenticator.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/auth/UnsupportedDigestAlgorithmException.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/HttpClientBuilder.java
Fixed typo for enum name Postion to Position in classes H2AsyncClientBuilder, HttpAsyncClientBuilder and HttpClientBuilder
=> Fixed typo for enum name Postion to Position

httpclient5/src/main/java/org/apache/hc/client5/http/ssl/DefaultHostnameVerifier.java, httpclient5/src/test/java/org/apache/hc/client5/http/ssl/CertificatesToPlayWith.java, httpclient5/src/test/java/org/apache/hc/client5/http/ssl/TestDefaultHostnameVerifier.java
https://issues.apache.org/jira/browse/HTTPCLIENT-2149
=> HTTPCLIENT-2149: When no dNSName, match against CN

httpclient5-fluent/src/main/java/org/apache/hc/client5/http/fluent/Executor.java
https://issues.apache.org/jira/browse/HTTPCLIENT-2148
=> HTTPCLIENT-2148: fluent Executor volatile access thread safety

httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/HttpCacheEntryMatcher.java, httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/HttpTestUtils.java, httpclient5-win/src/main/java/org/apache/hc/client5/http/impl/win/WinHttpClients.java, httpclient5-win/src/main/java/org/apache/hc/client5/http/impl/win/WindowsNegotiateScheme.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/auth/NTLMEngineImpl.java, httpclient5/src/test/java/org/apache/hc/client5/http/ContentTypeMatcher.java, httpclient5/src/test/java/org/apache/hc/client5/http/HeaderMatcher.java, httpclient5/src/test/java/org/apache/hc/client5/http/NameValuePairsMatcher.java
=> Simplify conditions and avoid extra checks.

httpclient5/src/test/java/org/apache/hc/client5/http/utils/TestDnsUtils.java
Name was missing a 't': <code>Tes<ins>t</ins>DnsUtils.java</code>
=> Fix bad test class name

httpclient5/src/main/java/org/apache/hc/client5/http/CircularRedirectException.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/H2AsyncClientBuilder.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/HttpAsyncClientBuilder.java
Add the option to set an IOSessionListener on HttpAsyncClientBuilder
=> Async HttpClient builders to support custom IOSessionListener 

httpclient5/src/test/java/org/apache/hc/client5/http/impl/classic/TestCloseableHttpClient.java
=> Refactor testcase

httpclient5/src/main/java/org/apache/hc/client5/http/impl/DefaultAuthenticationStrategy.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/AsyncConnectExec.java
- Remove redundant if
- Remove unused local variable
=> Minor cleanup

httpclient5/src/test/java/org/apache/hc/client5/http/examples/ClientProxyAuthentication.java
Update to the `ClientAuthenticationProxy` example to be runnable.
=> chore: update ClientProxyAuthenticationExample

httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/AsyncCachingExec.java, httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachingExec.java, httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestCachingExecChain.java
Complete support for RFC5861: Stale-While-Revalidate and Stale-If-Error
Description:
This pull request is a continuation of [`dc9b7b0`](https://github.com/apache/httpcomponents-client/commit/dc9b7b0f03df55bf88a0e638d900ed2b6206c0be) and aims to provide complete support for the rules of RFC5861, specifically covering the Stale-If-Error directive.
Changes include:
1. Updated CachingExec and AsyncCachingExec to handle stale-if-error directive as per RFC5861 rules. In case of an exception (e.g., IOException), the stale response will be served if the stale-if-error directive is enabled.
2. Added a new test case testStaleIfErrorEnabledWithIOException() to verify the behavior of serving a stale response when stale-if-error is enabled, and an exception occurs.
This PR should ensures that our …
=> Complete support for Stale-While-Revalidate and Stale-If-Error

httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/AIMDBackoffManager.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/BackoffStrategyExec.java, httpclient5/src/test/java/org/apache/hc/client5/http/impl/classic/TestAIMDBackoffManager.java
In this commit, we have made several improvements to the AIMDBackoffManager class:
* Replaced volatile variables with AtomicReference and AtomicInteger to ensure better thread-safety and atomic operations.
* Updated the @Contract annotation to reflect the new thread-safe behavior of the class.
* Added parameter validation checks to public methods for better error handling and prevention of incorrect usage.
* Improved the code readability and organization by separating sections of the class with blank lines and consistent indentation.
=> Improve AIMDBackoffManager with atomic references, thread-safety, and parameter checks

httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/AIMDBackoffManager.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/AbstractBackoff.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/ExponentialBackoffManager.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/LinearBackoffManager.java, httpclient5/src/test/java/org/apache/hc/client5/http/impl/classic/TestExponentialBackoffManager.java, httpclient5/src/test/java/org/apache/hc/client5/http/impl/classic/TestLinearBackoffManager.java
- Create AbstractBackoff class as a base for different backoff strategies
- Add LinearBackoffManager class for implementing linear backoff algorithm in networking and communication systems. This class provides a thread-safe and configurable implementation of linear backoff, allowing for gradual adjustment of maximum connection pool sizes for a given route based on traffic and other factors. The class supports customizable cool-down periods and increment values for each route, and uses a ConcurrentHashMap to ensure thread safety and accurate tracking of backoff and probe attempts
- Implement ExponentialBackoffManager for connection pool control.
This commit introduces the ExponentialBackoffManager class, which manages the connection pool control for HTTP routes based on the Exponential …
=> HTTPCLIENT-2272  - Add AbstractBackoff, LinearBackoffManager, and ExponentialBackoffManager classes

httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachingExecBase.java, httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestCachingExecChain.java
Implemented an enhancement to add a heuristic expiration warning to cached responses when the freshness lifetime and current age are both greater than one day. This warning, indicated by the '113' code, helps in identifying potential staleness in cached data and aligns with the HTTP caching specifications.
=> HTTPCLIENT-2275 -Add heuristic expiration warning to cached responses

httpclient5-cache/src/main/java/org/apache/hc/client5/http/cache/Resource.java, httpclient5/src/main/java/org/apache/hc/client5/http/entity/DecompressingEntity.java, httpclient5/src/main/java/org/apache/hc/client5/http/entity/EntityBuilder.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/nio/PoolingAsyncClientConnectionManager.java
Mostly missing Javadoc in org.apache.hc.client5.http.entity and minor clean ups
=> Mostly missing Javadoc in org.apache.hc.client5.http.entity

httpclient5-testing/src/test/java/org/apache/hc/client5/testing/sync/TestSSLSocketFactory.java, httpclient5/src/main/java/org/apache/hc/client5/http/ssl/SSLConnectionSocketFactory.java
https://issues.apache.org/jira/browse/HTTPCLIENT-2305
=> HTTPCLIENT-2305: SSLConnectionSocketFactory allows socket.connect to be decorated

httpclient5-cache/src/main/java/org/apache/hc/client5/http/cache/HttpCacheEntry.java, httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/AsyncCachingExec.java, httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/BasicHttpAsyncCache.java, httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/BasicHttpCache.java, httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachedHttpResponseGenerator.java, httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachedResponseSuitabilityChecker.java, httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachingExec.java, httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/ConditionalRequestBuilder.java, httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestCachingExecChain.java, httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestConditionalRequestBuilder.java, httpclient5/src/main/java/org/apache/hc/client5/http/protocol/RequestIfRange.java, httpclient5/src/main/java/org/apache/hc/client5/http/validator/ETag.java, httpclient5/src/main/java/org/apache/hc/client5/http/validator/ValidatorType.java, httpclient5/src/test/java/org/apache/hc/client5/http/validator/TestETag.java
* ETag / validator API
* Existing code improved to make use of higher level ETag API
=> ETag API / improved ETag handling

httpclient5-cache/src/main/java/org/apache/hc/client5/http/cache/ResponseCacheControl.java, httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/AsyncCachingExec.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/InternalH2AsyncExecRuntime.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/ContentCompressionExec.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/LinearBackoffManager.java, httpclient5/src/main/java/org/apache/hc/client5/http/protocol/RequestValidateTrace.java
- Corrected logger name in LinearBackoffManager
- Removed unused private fields and local variables
=> Optimizations

httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/AsyncHttpRequestRetryExec.java, httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/HttpRequestRetryExec.java
This change-set should fix [HTTPCLIENT-2371](https://issues.apache.org/jira/browse/HTTPCLIENT-2371) by logging request re-execution at INFO priority in case of an I/O error, status 503 or status 429. It also makes logging consistent between classic and async implementations
=> HTTPCLIENT-2371: Logging of request re-execution at INFO priority
