apache/httpcomponents-client

httpclient/src/main/java/org/apache/http/impl/cookie/PublicSuffixDomainFilter.java

Ok, second try. Now it seems to be correct.
The fix matches the behaviour of the BasicDomainHandler.
Hans-Peter

HTTPCLIENT-1904: check cookie domain for null

---

fluent-hc/pom.xml
httpclient-cache/pom.xml
httpclient-win/pom.xml
httpclient/pom.xml
httpmime/pom.xml

Add Automatic-Module-Name in manifest so Java9 modular applications can depend on this library.
Follow up pull request to a [similar PR](https://github.com/apache/httpcomponents-core/pull/65) in httpcomponents-core repo

Add Automatic-Module-Name in manifest 

---

httpclient/src/main/java/org/apache/http/impl/client/BasicCookieStore.java

HttpClient 4.5.4 modified BasicCookieStore to introduce a new
ReadWriteLock field to improve performance. Unfortunately this
also changed the serialized data structure, and any objects
serialized using HttpClient 4.5.3 and before would be unusable
after restore in HttpClient 4.5.4 due to the new "lock" field
being null.
The fix is to change "lock" to be transient, and ensure it is
correctly instantiated upon object restore. This restores
compatibility with HttpClient 4.5.3, as well as maintaining
compatible with the intermediate versions containing the
regression. This also avoids unnecessary serialization of
the new "lock" field, which does not need to be persisted.

Fix HttpClient 4.5.4 regression in BasicCookieStore serialization.

---

httpclient5/src/main/java/org/apache/hc/client5/http/config/RequestConfig.java

This change makes request cancellation behavior more consistent across different client types (blocking, non-blocking HTTP/1.1, and HTTP/2).

Enable hard cancellation by default

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/nio/PoolingAsyncClientConnectionManagerBuilder.java

Wrong argument name in setConnPoolPolicy results with self assignment of variable

Fix PoolingAsyncClientConnectionManagerBuilder

---

httpclient/src/main/java/org/apache/http/client/HttpResponseException.java
httpclient/src/test/java/org/apache/http/impl/client/TestAbstractResponseHandler.java

Tomcat 8.5 omits reason phrase. 
So in order to have more informative logs I would suggest using statusCode instead.
It can happen either in the constructor or when passing parameters to it (in AbstractResponseHandler)

replace empty HttpResponseException.message with statusCode

---

httpclient5/src/main/java/org/apache/hc/client5/http/HttpResponseException.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/classic/TestAbstractHttpClientResponseHandler.java

The #getMessage() now properly consists of the status code as such and the
optional reason phrase. Moreover, the pure reason phrase can be retrieved
via #getReasonPhrase.
This is an improved version of #126.

Improve HttpResponseException#getMessage()

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/HttpClientBuilder.java

Naive approach works for me. I am not certain whether the `@see` is necessary. I think not.

[HTTPCLIENT-1952] Allow default User Agent to be disabled

---

httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachedHttpResponseGenerator.java

Some well known proxies respond with Content-Length=0, when returning 304. For robustness, always use the cached entity's content length, as modern browsers do.

Always use the cached entity's content length.

---

httpclient-cache/src/main/java/org/apache/http/impl/client/cache/CachingExec.java
httpclient/src/main/java-deprecated/org/apache/http/impl/client/DefaultRedirectHandler.java
httpclient/src/main/java-deprecated/org/apache/http/impl/client/DefaultRequestDirector.java
httpclient/src/main/java/org/apache/http/client/config/RequestConfig.java
httpclient/src/main/java/org/apache/http/client/utils/URIUtils.java
httpclient/src/main/java/org/apache/http/impl/client/DefaultRedirectStrategy.java
httpclient/src/main/java/org/apache/http/impl/execchain/MinimalClientExec.java
httpclient/src/main/java/org/apache/http/impl/execchain/ProtocolExec.java
httpclient/src/test/java/org/apache/http/client/utils/TestURIUtils.java
httpclient/src/test/java/org/apache/http/impl/client/TestDefaultRedirectStrategy.java
httpclient/src/test/java/org/apache/http/impl/execchain/TestProtocolExec.java

https://issues.apache.org/jira/browse/HTTPCLIENT-1968
Make the normalization optional (default == true) based on `RequestConfig` setting. All the legacy spots just keep "default" behaviour, while the current bits are obeying the new param in request config.

HTTPCLIENT-1968

---

httpclient/src/main/java/org/apache/http/conn/ssl/SSLConnectionSocketFactory.java
httpclient/src/test/java/org/apache/http/conn/ssl/TestSSLSocketFactory.java

Please consider a patch for [HTTPCLIENT-1969](https://issues.apache.org/jira/browse/HTTPCLIENT-1969):
- Defined a list of weak algorithms which may be used in a TLS connection. The list is based on the latest settings in modern OpenJDK, see [java.security](https://hg.openjdk.java.net/jdk/jdk/file/1019c97e1bde/src/java.base/share/conf/security/java.security#l678) file (EXPORT ciphers are also disabled in modern OpenJDK by default)
- Updated `SSLConnectionSocketFactory` to filter out weak ciphers if cipher suites are not explicitly set.
Please note that the test passes with latest Java versions even without patching `SSLConnectionSocketFactory` because latest Java versions disable weak ciphers by default. The filtering mechanism blocks weak ciphers in case older Java versions are used.

HTTPCLIENT-1969: Filter out weak cipher suites

---

httpclient/src/main/java/org/apache/http/impl/execchain/MainClientExec.java

Changed route tracking of proxy to not default to false and instead to
use the route's secure value. this allow routes to proxies to be https and
not tunnel/CONNECT.  All test pass with this change.

Changed route tracking of proxy to not default to false

---

httpclient/src/main/java/org/apache/http/client/config/RequestConfig.java
httpclient/src/test/java/org/apache/http/client/config/TestRequestConfig.java

Add normalize URI to RequestConfig copy constructor
https://issues.apache.org/jira/browse/HTTPCLIENT-1984

HTTPCLIENT-1984: Add normalize URI to RequestConfig copy constructor

---

httpclient/src/main/java/org/apache/http/client/utils/URIBuilder.java
httpclient/src/test/java/org/apache/http/client/utils/TestURIUtils.java

isPathEmpty should verify if encodedPath member is an empty string.
Otherwise, [this code](https://github.com/apache/httpcomponents-client/blob/4.5.x/httpclient/src/main/java/org/apache/http/client/utils/URIUtils.java#L229) in URIUtils.rewriteURI will evaluate to false when normalization is disabled.
Before 4.5.6, URIUtils.rewriteURI method used [TextUtils#isEmpty method](https://github.com/apache/httpcomponents-core/blob/master/httpcore5/src/main/java/org/apache/hc/core5/util/TextUtils.java#L42) which checked for both null and empty string case.
* Added a new unit test. The test failed before including the empty string check

Fix bug in URIBuilder#isPathEmpty method 

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/Wire.java

DEL characters should be converted to [0x7f] in Wire traces otherwise they are difficult to see in logs.

Escape DEL character when tracing

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/MainClientExec.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/MinimalHttpClient.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/ResponseEntityProxy.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/classic/TestResponseEntityProxy.java

1. MainClientExec changed in a way to recognize chunked encoding and create correct http entity wrapper for it, implemented a new http entity wrapper which works with ChunkedInputStream to reach trailers and propagate them to HttpEntity.getTrailers() API
2. Fixed a typo in ResponseEntityProxy.enhance() method name

HTTPCLIENT-1992: Impossible to access trailer-headers 

---

httpclient5/src/main/java/org/apache/hc/client5/http/config/RequestConfig.java

I linked each builder method to its corresponding getter in the built object. However, the builder methods are the primary interface for users, so I think it should hold the primary javadocs instead.

Add RequestConfig builder javadocs

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/PoolingHttpClientConnectionManager.java

The purpose of this change is to allow stale checking all the time, in previous versions of HttpClient this was accomplished by staleConnectionCheckEnabled=true which is now removed, this adds that idea back

HTTPCLIENT-2028: Now allowing 0 for validateAfterInactivity

---

httpclient5/src/main/java/org/apache/hc/client5/http/psl/PublicSuffixMatcher.java
httpclient5/src/main/java/org/apache/hc/client5/http/ssl/DefaultHostnameVerifier.java
httpclient5/src/test/java/org/apache/hc/client5/http/psl/TestPublicSuffixMatcher.java
httpclient5/src/test/java/org/apache/hc/client5/http/ssl/TestDefaultHostnameVerifier.java
httpclient5/src/test/resources/suffixlistmatcher.txt

This fixes the behaviour of PublicSuffixMatcher::getDomainRoot in the case when you feed it a hostname for which NO rule has been defined; and you specify an expected domaintype (i.e. either ICANN or PRIVATE).
Notable changes for reviewers:
- PublicSuffixMatcher load(final InputStream in)  is now public to make testing a lot easier and also useful for downstream users.
- I had to change the test for HTTPCLIENT-1997 also because that used an invalid domain name in their test. So instead of "cloud.a" it now uses "cloud.com" instead.

HTTPCLIENT-2030: Fix PublicSuffixMatcher::getDomainRoot on invalid hostnames

---

httpclient/src/main/java/org/apache/http/conn/ssl/DefaultHostnameVerifier.java
httpclient/src/main/java/org/apache/http/conn/util/PublicSuffixMatcher.java
httpclient/src/test/java/org/apache/http/conn/ssl/TestDefaultHostnameVerifier.java
httpclient/src/test/java/org/apache/http/conn/util/TestPublicSuffixMatcher.java
httpclient/src/test/resources/suffixlistmatcher.txt

This is an as exact as possible backport of https://github.com/apache/httpcomponents-client/pull/174 to the 4.5.x branch.
Only real differences are file locations and the UTF_8 had to be defined manually.

HTTPCLIENT-2030: Fix PublicSuffixMatcher::getDomainRoot on invalid hostnames (4.5.x)

---

httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/HttpByteArrayCacheEntrySerializer.java

MemcachedCacheEntryHttp inner class NoAgeCacheValidityPolicy should be static.
Add missing javadoc @param and @return entries to MemcachedCacheEntryHttp.
Remove extra blank lines.

HttpByteArrayCacheEntrySerializer minor code cleanup for HTTPCORE-615.

---

httpclient5/src/main/java/org/apache/hc/client5/http/ssl/DefaultHostnameVerifier.java

This change ensures that during hostname verification the public suffix
list is only used to prevent wildcard matching against entire TLDs (e.g.
`*.com`). Currently, private domains are also being matched against,
which is preventing reasonable wildcards (such as
`*.s3.eu-central-1.amazonaws.com`) from being respected.

DefaultHostnameVerifier: Match DNS and CN names against ICANN domains

---

httpclient5-testing/pom.xml
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/async/AbstractHttpReactiveFundamentalsTest.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/async/AbstractServerTestBase.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/async/TestH2MinimalReactive.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/async/TestH2Reactive.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/async/TestHttp1Reactive.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/async/TestHttpMinimalReactive.java

This commit adds test coverage for the `:httpcore5-reactive` bindings,
using different types of clients and protocols. Not all of these tests
pass, as some of them have uncovered new bugs. In particular:
* `testSequentialHeadRequests` always fails and is currently ignored
* The `testSequentialPostRequests` and `testConcurrentPostRequests` test
cases fail non-deterministically

Add reactive test coverage

---

httpclient5/src/main/java/org/apache/hc/client5/http/classic/methods/ClassicHttpRequests.java
httpclient5/src/test/java/org/apache/hc/client5/http/classic/methods/TestClassicHttpRequests.java

Now that ClassicHttpRequests is no longer an enum, I need to way to generically build requests from method names.

Build requests from method names

---

RELEASE_NOTES.txt
httpclient5/src/main/java/org/apache/hc/client5/http/async/methods/BasicHttpRequests.java
httpclient5/src/main/java/org/apache/hc/client5/http/async/methods/SimpleHttpRequests.java
httpclient5/src/main/java/org/apache/hc/client5/http/classic/methods/ClassicHttpRequests.java
httpclient5/src/test/java/org/apache/hc/client5/http/async/methods/SimpleBasicHttpRequests.java

generically build requests from method names. Update all factory classes
with matching APIs for Method and String method name inputs.

Now that ClassicHttpRequests is no longer an enum, we need to way to

---

httpclient/src/main/java/org/apache/http/impl/execchain/RedirectExec.java
httpclient/src/test/java/org/apache/http/impl/client/integration/TestRedirects.java

@michael-o It looks like handling of redirects of entity enclosing methods has been broken for some while.

HTTPCLIENT-2052

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/MinimalH2AsyncClient.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/MinimalHttpAsyncClient.java

Fixes JIRA HTTPCLIENT-2059
According to the javadoc in `HttpAsyncClient`, the `HttpContext` parameter can be null. However, `MinimalHttpAsyncClient` and `MinimalH2AsyncClient` both reject null `HttpContext`.

Fix NPE for null HttpContext in MinimalHttpAsyncClient and MinimalH2AsyncClient

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/HttpClientBuilder.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/classic/TestHttpClientBuilder.java

Previously HttpClientBuilder methods addExecInterceptorFirst and
addExecInterceptorLast resulted in NullPointerExceptions because
the execInterceptors list had not been initialized yet.

HTTPCLIENT-2083: Fix NPE when classic client interceptors are added

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/PoolingHttpClientConnectionManager.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/nio/PoolingAsyncClientConnectionManager.java

Both connection managers agree on the meaning of a zero-duration
validateAfterInactivity value. Previously the documentation for
both suggested that zero resulted in no validation, however
the classic client would validate prior to each request and
the async client would never validate.
This commit standardizes behavior on the classic client, which
is consistent with hc4.x, allowing zero to force validation prior
to every request.

HTTPCLIENT-2094: ConnectionManager validateAfterInactivity zero duration agreement

---

httpclient5/src/main/java/org/apache/hc/client5/http/entity/mime/MultipartEntityBuilder.java

I've changed generateBoundary to use `ThreadLocalRandom` instead of creating a new `Random` every time, and I've replaced the `StringBuilder` with the faster `CharBuffer`.

Optimize MultipartEntityBuilder#generateBoundary

---

httpclient/src/main/java/org/apache/http/impl/cookie/BasicExpiresHandler.java

BasicExpiresHandler is annotated as immutable but is not.

BasicExpiresHandler is annotated as immutable but is not.

---

httpclient5/src/main/java/org/apache/hc/client5/http/ssl/SSLConnectionSocketFactory.java

SSLConnectionSocketFactory no longer overrides the socket timeout
with the connect timeout when an unlimited socket timeout is
configured. This matches behavior of HTTPCLIENT-2091.
Note that in scenarios where SocketConfig sets an infinite timeout
and the RequestConfig sets a bounded timeout, this change results
in the connect-timeout no longer applying to the TLS handshake.
This behavior can be retained by setting the expected timeout in
the SocketConfig.

HTTPCLIENT-2099: SSLConnectionSocketFactory timeout fix

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/PoolingHttpClientConnectionManager.java

I have verified that PoolingAsyncClientConnectionManager already handles the volatile field correctly.

HTTPCLIENT-2107: Threadsafe PoolingHttpClientConnectionManager field volatile access

---

httpclient-cache/src/main/java/org/apache/http/impl/client/cache/CacheEntryUpdater.java
httpclient-cache/src/test/java/org/apache/http/impl/client/cache/TestCacheEntryUpdater.java

I observed the following problem: `Transfer-Encoding` and
`Content-Length` headers should be mutually exclusive and because I use
chunked transfer, the `Transfer-Encoding` header is set in the response
while the `Content-Length` header is not. In case of a 304 during a
revalidation, the header contains Content-Length=0. Probably a proxy is
responsible for this, just like the comment "Some well-known proxies
respond with Content-Length=0, when returning 304" in the method
CachedHttpResponseGenerator::addMissingContentLengthHeader is saying. In
CacheEntryUpdater::mergeHeaders the Content-Length=0 is merged into the
cached entry, but the cached entry contains also a `Transfer-Encoding`
header, so in the cached entry these headers aren't mutually exclusive
anymore. Because of the …

Avoid updating Content-Length header in a 304 response.

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/ExecSupport.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/PoolingHttpClientConnectionManager.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/nio/PoolingAsyncClientConnectionManager.java

As discussed some time ago on the dev mailing list.

Use decimal numbers for endpoint/execution IDs

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/nio/PoolingAsyncClientConnectionManager.java

i have a problem here.
it doesn't support PingCommand When I use HTTP 1.1 protocol.  because AbstractHttp1StreamDuplexer.class doesn't support PingCommand.

PoolingAsyncClientConnectionManager incorrectly emits Ping commands to HTTP/1.1 endpoints 

---

httpclient5-testing/src/test/java/org/apache/hc/client5/testing/sync/TestMinimalClientRequestExecution.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/MinimalHttpClient.java

`NullPointerException` in `org.apache.hc.client5.http.impl.classic.MinimalHttpClient.doExecute(HttpHost, ClassicHttpRequest, HttpContext)`

[HTTPCLIENT-2124] NullPointerException in MinimalHttpClient.doExecute(HttpHost, ClassicHttpRequest, HttpContext)

---

httpclient5/src/main/java/org/apache/hc/client5/http/entity/mime/HttpRFC7578Multipart.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/BasicHttpClientConnectionManager.java
httpclient5/src/test/java/org/apache/hc/client5/http/entity/mime/HttpRFC7578MultipartTest.java

LGTM.com offers static analysis for open-source projects. It's based on CodeQL engine. The current report for Apache HttpClient is pretty good. There are only 19 findings. I had a look at them, and didn't find anything severe. Nevertheless, I'd like to propose fixing some minor findings and suppressing the rest. Suppressing the warnings would make it simpler to triage new issues in the future.
Here is a list of updates:
- Fixed a few possible null dereferences
- Fixed a few possible out-of-bound array ops
- Suppressed warnings for weak cryptographic algorithms for NTLM and Digest authentication schemes
- Suppressed a few false-positives for null dereference
- Suppressed a few warnings for overriding a synchronized method without synchronization
- Added a couple of test cases

Fixed and suppressed several findings from LGTM.com

---

.github/workflows/codeql-analysis.yml

GitHub now offers code scanning that is based on CodeQL (the same engine that is used in LGTM.com). Shortly, that's a static analysis tool that is able to catch various issues including security ones. Once enabled for pull requests, it would help with catching issues earlier.
The scan may be run via [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/enabling-code-scanning-for-a-repository#enabling-code-scanning-using-actions) for pull requests. Or, LGTM checks may be added, the instructions are [here](https://lgtm.com/help/lgtm/managing-automated-code-review).
How about enabling the scans for HttpClient? The proposed update creates a GitHub action that runs CodeQL scans for pull requests and the master branch. …

Set up CodeQL scans

---

.travis.yml

More and more software development is being done on ARM64 CPU architecture.
It would be good if HttpComponents Client is being regularly tested on ARM64.
Similar PR for HttpComponents Core: https://github.com/apache/httpcomponents-core/pull/228

Build and test on both AMD64 and ARM64

---

.travis.yml

The Graviton2 builder is available only on travis-ci.com. Apache uses travis-ci.org
Install Maven explicitly because it is not pre-installed on the ARM64 image for Trusty
Related-to: https://github.com/apache/httpcomponents-client/pull/265

Use 'arm64' instead of 'arm64-graviton2'

---

httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/HttpByteArrayCacheEntrySerializerTestUtils.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestByteArrayCacheEntrySerializer.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestHttpByteArrayCacheEntrySerializer.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestProtocolRequirements.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/async/AbstractHttpReactiveFundamentalsTest.java
httpclient5-win/src/main/java/org/apache/hc/client5/http/impl/win/WinHttpClients.java
httpclient5/src/main/java/org/apache/hc/client5/http/HttpRoute.java
httpclient5/src/main/java/org/apache/hc/client5/http/RouteTracker.java
httpclient5/src/main/java/org/apache/hc/client5/http/async/methods/SimpleBody.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/MinimalHttpAsyncClient.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/auth/BasicAuthCache.java

Each commit in this PR comprise one kind of cleanup/change:
- Use try-with-resources.
- Use Arrays.fill().
- Add missing @override.
- Simplify if/else.
- Remove redundant modifiers. …
- Remove redundant returns.

Master try w res and more

---

httpclient-cache/src/main/java/org/apache/http/impl/client/cache/CacheEntity.java

Remove `clone()` method that only calls `super` in `Object`.

Remove clone() method that only calls super in Object.

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/H2AsyncClientBuilder.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/HttpAsyncClientBuilder.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/HttpClientBuilder.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/classic/TestHttpClientBuilderInterceptors.java

When `addExecInterceptorLast` is called on an `HttpClientBuilder`, `HttpAsyncClientBuilder` or `H2AsyncClientBuilder`, the given executor is added as last element of the executor chain. That may seem correct, but it causes them to be ignored. The reason is the `*MainClientExec` that's initially the last element. In all three cases, this does not delegate to the chain. As a result, anything added with `addExecInterceptorLast` is currently completely ignored.
This change adds the interceptor as last in the chain of actual interceptors, just before the `*MainClientExec` which I don't consider an interceptor. It's the same as the workaround I've been applying right now which works just fine.

Add interceptors before MAIN_TRANSPORT so they won't be ignored

---

pom.xml

update scm publish location to better show publication to staging of generated documentation in an unversioned LATEST directory
upcoming website PR will provide the glue of this staging documentation to its released/versioned copy and the main unversioned site

scm-publish to /components/httpcomponents-client-5.0.x/LATEST

---

httpclient5/src/main/java/org/apache/hc/client5/http/protocol/ResponseProcessCookies.java

Fix typo on method name from `formatCooke` to `formatCookie`

Fix typo on cookie formatting method

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/auth/GGSSchemeBase.java

1. At the beginning of the negotiate, no token is defined in "WWW-Authenticate: Negotiate".
2. Kerberos expects HTTP.

Fix the issues causing Kerberos/SPNego to fail

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/BasicHttpClientConnectionManager.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/PoolingHttpClientConnectionManager.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/PoolingHttpClientConnectionManagerBuilder.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/nio/PoolingAsyncClientConnectionManagerBuilder.java

@carterkozak @rschmitt Blocking connection managers now validate connections after inactivity of more than 2s by default. The behavior of async connection managers remains unchanged. 
Please review.

Blocking connection managers to validate connections by default

---

httpclient5-testing/src/test/java/org/apache/hc/client5/testing/async/AbstractHttp1IntegrationTestBase.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/async/TestH2Async.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/async/TestH2AsyncRedirect.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/async/TestH2ClientAuthentication.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/async/TestH2Reactive.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/async/TestHttp1Async.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/async/TestHttp1AsyncRedirects.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/async/TestHttp1AsyncStatefulConnManagement.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/async/TestHttp1ClientAuthentication.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/async/TestHttp1Reactive.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/sync/LocalServerTestBase.java
httpclient5/src/main/java/org/apache/hc/client5/http/config/ConnectionConfig.java
httpclient5/src/main/java/org/apache/hc/client5/http/config/RequestConfig.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/H2AsyncClientBuilder.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/InternalH2AsyncClient.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/InternalH2AsyncExecRuntime.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/InternalH2ConnPool.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/MinimalH2AsyncClient.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/BasicHttpClientConnectionManager.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/PoolingHttpClientConnectionManager.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/PoolingHttpClientConnectionManagerBuilder.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/nio/PoolingAsyncClientConnectionManager.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/nio/PoolingAsyncClientConnectionManagerBuilder.java
httpclient5/src/test/java/org/apache/hc/client5/http/config/TestRequestConfig.java
httpclient5/src/test/java/org/apache/hc/client5/http/examples/ClientConfiguration.java

@rschmitt @carterkozak @michael-o @garydgregory I would like to propose the following changes to HttpClient 5.x configuration APIs. In essence all configuration parameters related to connection management and initialization have been moved from `RequestConfig` to a new config class. 
This is just a draft at this point. You are welcome to propose alternative ideas, better class names and so on.

Connection management configuration

---

doap_HttpComponents_Client.rdf
fluent-hc/pom.xml
httpclient-cache/pom.xml
httpclient-osgi/pom.xml
httpclient-win/pom.xml
httpclient/pom.xml
httpmime/pom.xml

Maven Central (https://search.maven.org/artifact/org.apache.httpcomponents/httpclient/4.5.13/jar
) tells wrong URL for the project.

Updating project URL to include '-ga' suffix

---

httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/AsyncCachingExec.java
httpclient5-testing/src/main/java/org/apache/hc/client5/testing/async/ServiceUnavailableAsyncDecorator.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/async/TestHttp1RequestReExecution.java
httpclient5/src/main/java/org/apache/hc/client5/http/async/AsyncExecChain.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/AsyncHttpRequestRetryExec.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/AsyncRedirectExec.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/InternalAbstractHttpAsyncClient.java

@rschmitt Please let me know if you have any objections to this change-set. 
@michael-o Please also take a look at `HttpRequestRetryStrategy` related changes and let me know if everything looks OK.

HTTPCLIENT-2152

---

httpclient5-testing/src/test/java/org/apache/hc/client5/testing/async/TestHttp1Async.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/sync/TestClientRequestExecution.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/InternalExecRuntime.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/PoolingHttpClientConnectionManager.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/nio/PoolingAsyncClientConnectionManager.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/io/TestPoolingHttpClientConnectionManager.java

@rschmitt Fundamentally, the core problem here is whose responsibility it is to release a pool entry back to the pool if the lease request simultaneously succeeds and gets cancelled. 
This is not a _final_ fix but merely a concept. I still need to figure the back way of dealing with the problem. I also need to fix the same defect in the async connection manager implementation.
What truly baffles me is how come this issue has never been reported with HttpClient 4.5 given it appears to be equally affected.

Connection lease request cancellation bug

---

httpclient/src/main/java/org/apache/http/impl/client/DefaultHttpRequestRetryHandler.java
httpclient/src/test/java/org/apache/http/impl/client/TestDefaultHttpRequestRetryHandler.java

As discussed in the mailing list discussion here[1], the commit here includes `java.net.NoRouteToHostException` to the set of exception types, for which request retries are disabled by default. The commit also has a test case which reproduces the issue and verifies the fix.
I had a look at the `java.net.SocketException` hieararchy. It has `BindException`, `ConnectException`, `NoRouteToHostException` and `PortUnreachableException` as its subclasses. The `BindException` is not relevant while connecting as a client. The `ConnectException` is already included in the default set of non-retriable exception types in this `DefaultHttpRequestRetryHandler` class. The `PortUnreachableException` is for ICMP port unreachable cases, so it isn't relevant in this flow. So that leaves only …

Don't retry a request for NoRouteToHostException

---

httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/ManagedHttpCacheStorage.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/cache/ManagedHttpCacheStorageTest.java

And reuse code for `this.active.compareAndSet(true, false);` validations.

Expose method to check the cache is still active.

---

httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/WarningValue.java

No need check again if the Chart is `\` or not.
`
else if (c == '\"') {
foundEnd = true;
offs++;
} else if (c != '\"' && !isControl(c)) {
`

Avoid redundant validation of '\"'. Its checked before.

---

pom.xml

Bumping log4j due to CVE-2021-44228

Bump log4j to 2.16.0

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/AsyncHttpRequestRetryExec.java

https://issues.apache.org/jira/browse/HTTPCLIENT-2194
We found that our async retries were failing because there was no body being set.  Releasing the entityProducer resets the starting point to 0 and resolved the issue for us.

Httpclient-2194 async retries not including body

---

httpclient5/src/main/java/org/apache/hc/client5/http/ssl/AbstractClientTlsStrategy.java

Updated AbstractClientTlsStrategy to pass only the HttpVersionPolicy instead of the entire TlsConfig to H2TlsSupport.selectApplicationProtocols() method, since this is the expected data type.

HTTPCLIENT-2198, Fixed AbstractClientTlsStrategy to respect HttpVersionPolicy

---

httpclient5/src/main/java/org/apache/hc/client5/http/config/TlsConfig.java
httpclient5/src/main/java/org/apache/hc/client5/http/ssl/AbstractClientTlsStrategy.java

Replaced calls to Arrays.asList() with Arrays.toString(), which allows for null argument.

HTTPCLIENT-2198, Fixed NPE in TlsConfig.toString()

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/nio/DefaultAsyncClientConnectionOperator.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/nio/PoolingAsyncClientConnectionManager.java
httpclient5/src/main/java/org/apache/hc/client5/http/nio/AsyncClientConnectionOperator.java

Pass HttpContext to AsyncClientConnectionOperator, change is non-breaking by introducing two default methods:
```
default void upgrade(ManagedAsyncClientConnection conn, HttpHost host, Object attachment, HttpContext context) {
upgrade(conn, host, attachment);
}
default Future<ManagedAsyncClientConnection> connect(
ConnectionInitiator connectionInitiator,
HttpHost host,
SocketAddress localAddress,
Timeout connectTimeout,
Object attachment,
HttpContext context,
FutureCallback<ManagedAsyncClientConnection> callback) {
return connect(connectionInitiator, host, localAddress, connectTimeout,
attachment, callback);
}
```

HTTPCLIENT-2209: Pass HttpContext to AsyncClientConnectionOperator

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/InternalAbstractHttpAsyncClient.java

This thread pool is currently preventing applications with unclosed clients from exiting. Anyone who needs a client to finish a call before shutting down can continue to block on a non-daemon thread, but now someone needing an immediate shutdown is able to actually trigger one.

Create daemon threads in InternalAbstractHttpAsyncClient

---

NOTICE.txt

Updated the copyright in notice to the present year 2022.
- This came up in a discussion on PR for including this notice in Apache Iceberg 
- https://github.com/apache/iceberg/pull/4688#discussion_r864419657

Updated copyright statement in NOTICE.txt

---

httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/memcached/SHA256KeyHashingScheme.java
httpclient5-testing/src/main/java/org/apache/hc/client5/testing/auth/BasicAuthTokenExtractor.java
httpclient5-win/src/main/java/org/apache/hc/client5/http/impl/win/WindowsNegotiateScheme.java
httpclient5/pom.xml
httpclient5/src/main/java/org/apache/hc/client5/http/entity/mime/HttpRFC7578Multipart.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/auth/BasicScheme.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/auth/GGSSchemeBase.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/auth/NTLMEngineImpl.java
httpclient5/src/main/java/org/apache/hc/client5/http/utils/Base64.java
httpclient5/src/main/java/org/apache/hc/client5/http/utils/Hex.java
httpclient5/src/test/java/org/apache/hc/client5/http/entity/mime/HttpRFC7578MultipartTest.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/auth/TestBasicScheme.java
httpclient5/src/test/java/org/apache/hc/client5/http/utils/TestBase64.java
pom.xml

Add a utility to implement the parts of commons-codec Base64 that are needed by httpcomponents-client on top of Java 8 `java.util.Base64`,
Also updated the relevant places to make use of this new utility.
One note - I do not know what the Android compatibility needs are, or what portions of Java 8 are readily available in the versions of Android that are expected to be supported.  
From here: https://developer.android.com/reference/java/util/Base64
It appears that Api Level 26 added support.
At first glance, this change almost removes the need for the production commons-codec dependency. The remaining use is for hex-encoding, and a reused exception. These could easily also be removed. I have added a separate commit to implement this.

HTTPCLIENT-2218: Use Java 8 Base64 utility

---

httpclient5-testing/src/test/java/org/apache/hc/client5/testing/sync/TestConnectionReuse.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/ResponseEntityProxy.java

[HTTPCLIENT-2221](https://issues.apache.org/jira/browse/HTTPCLIENT-2221)
Previously, a partially consumed response body closed via
CloseableHttpResponse.close or HttpEntity.close would fully consume
remaining bytes (via close), however it would not release the
connection for reuse.
If CloseableHttpResponse.close was called, it would follow the close
with a discard/disconnect, however if only the entity was closed,
the connection would remain in a checked-out (leaked) state.
Now, we take advantage of the fact that closing a response stream
on any reusable connection is required to drain bytes on closure.
Failures are detected by writeTo and the stream returned by
getContent, so we can be confident that we will not return a
broken connection to the pool.

HTTPCLIENT-2221 Closing a classic response/entity allows connection reuse

---

httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachedHttpResponseGenerator.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachingExecBase.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/DefaultAsyncCacheInvalidator.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/DefaultCacheInvalidator.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/DefaultRedirectStrategy.java
httpclient5/src/main/java/org/apache/hc/client5/http/protocol/ResponseProcessCookies.java

Use HTTP header name constants instead of string literals.

Use HTTP header name constants

---

httpclient5/src/main/java/org/apache/hc/client5/http/cookie/CookiePriorityComparator.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/cookie/BasicClientCookie.java

Avoid unnecessary use of Instant.toEpochMilli by using Instant.compareTo
to compare Instants direclty

Avoid unnecessary use of Instant.toEpochMilli

---

RELEASE_NOTES.txt
httpclient5/src/main/java/org/apache/hc/client5/http/HttpRoute.java
httpclient5/src/main/java/org/apache/hc/client5/http/RouteTracker.java
httpclient5/src/main/java/org/apache/hc/client5/http/auth/AuthScope.java
httpclient5/src/main/java/org/apache/hc/client5/http/auth/BasicUserPrincipal.java
httpclient5/src/main/java/org/apache/hc/client5/http/auth/NTCredentials.java
httpclient5/src/main/java/org/apache/hc/client5/http/auth/NTUserPrincipal.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/auth/BasicAuthCache.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/InternalExecRuntime.java

This PR addresses an issue when interrupting a thread when using an `HttpClient` with the `PoolingHttpClientConnectionManager`. If the pool reaches the max size, and the client is waiting on a lease request, and if the client thread is interrupted, the lease will continue to wait and the pool will not free up until the lease request timeout is reached. This change will explicitly cancel the lease request if an exception occurs.

Cancel connection request on exception

---

httpclient5/src/main/java/org/apache/hc/client5/http/ssl/SSLConnectionSocketFactory.java

Some implementations might depend on a variable present in the `HttpContext` which is available in most other methods.

feature(SSLConnectionSocketFactory): Pass HttpContext to prepareSocket method

---

httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/HttpByteArrayCacheEntrySerializer.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/PoolingHttpClientConnectionManager.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/nio/PoolingAsyncClientConnectionManager.java

Inner classes that do not reference their enclosing instances can be made static.
This prevents a common cause of memory leaks and uses less memory per instance of the class.
* InnerClassMayBeStatic (3)

refactor: refactor bad smell InnerClassMayBeStatic

---

httpclient5/src/main/java/org/apache/hc/client5/http/SystemDefaultDnsResolver.java
httpclient5/src/test/java/org/apache/hc/client5/http/SystemDefaultDnsResolverTest.java

This pull request addresses issue LLv6 literals in URLs, where LLv6 literals in URLs are not properly handled by HttpClient due to a limitation in the Java standard method InetAddress.getAllByName(host). Specifically, when constructing a URL with an LLv6 literal, the % sign that prefixes the ZoneID must be quoted as %25 according to RFC 6874. However, HttpClient does not support quoted host literals.
To work around this limitation, this pull request modifies the SystemDefaultDnsResolver class to strip the IPv6 zone identifier from the host string before calling InetAddress.getAllByName(host). This allows HttpClient to handle LLv6 literals in URLs that conform to RFC 6874.

Fix issue with LLv6 literals in URLs

---

httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/BasicHttpCache.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestBasicHttpCache.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestProtocolRecommendations.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestProtocolRequirements.java

Fix handling of cache entries with variants that have different ETag values
Previously, the `getCacheEntry` method was not correctly handling cache entries with variants that had different ETag values. This was leading to incorrect behavior when serving cached responses, which resulted in failing tests.
This commit fixes the issue by correctly identifying the cache entry using the request's cache key, and then selecting the variant with the matching ETag value. If there is no matching variant, the cache entry is considered stale and a new response is fetched from the origin server.
This change is aligned with RFC7232 section 2.3 which states that when an origin server sends multiple representations of a resource with different ETag values, a cache should cache all of them. This means that …

Fix handling of cached responses with variants and different ETag values.

---

httpclient5-cache/src/main/java/org/apache/hc/client5/http/cache/HeaderConstants.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CacheControl.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CacheControlHeaderParser.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/ResponseCachingPolicy.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/CacheControlParserTest.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestCachingExecChain.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestResponseCachingPolicy.java

This pull request adds a fix for the calculateFreshnessLifetime method in the HttpResponseCache class. The method calculates the freshness lifetime of a response based on the headers in the response and follows the algorithm for calculating the freshness lifetime described in RFC 7234, section 4.2.1.
The method takes into account the s-maxage, max-age, Expires, and Date headers as follows:
- If the s-maxage directive is present in the Cache-Control header of the response, its value is used as the freshness lifetime for shared caches, which typically serve multiple users or clients.
- If the max-age directive is present in the Cache-Control header of the response, its value is used as the freshness lifetime for private caches, which serve a single user or client.
- If the Expires header is …

Fix calculation of freshness lifetime in HttpResponse

---

httpclient/src/main/java/org/apache/http/impl/execchain/ResponseEntityProxy.java
httpclient/src/test/java/org/apache/http/impl/client/TestResponseEntityProxy.java
httpclient/src/test/java/org/apache/http/impl/execchain/TestResponseEntityProxy.java

This PR is backporting a change which was made to ResponseEntityProxy in v5.0. I understand that the 4.5.x branch is closed to any visible API changes. If these changes fall outside of the scope of what is permissible for this branch please let me know and reject the PR.

HTTPCLIENT-2263: Cannot Access Trailer-Headers in Chunked transfer-encoding

---

httpclient5-fluent/src/main/java/org/apache/hc/client5/http/fluent/ContentResponseHandler.java
httpclient5/src/main/java/org/apache/hc/client5/http/HttpResponseException.java

This pull request enhances ContentResponseHandler to be fault-tolerant by adding the ability to handle responses with null or empty bodies without throwing exceptions. If the response was successful (a 2xx status code), the Content object is returned. If no response body exists, Content.NO_CONTENT is returned.
This implementation of ContentResponseHandler overrides its methods to handle the response entity and transform it into the actual response object. This is designed to be efficient and use minimal memory.
This enhancement to ContentResponseHandler is intended to be used in scenarios where the response body may be null or empty, but the caller still needs to determine whether the response was successful or not. For example, when testing an HTTP API, the response body may be empty but …

Enhances ContentResponseHandler to be fault-tolerant 

---

httpclient5-cache/src/main/java/org/apache/hc/client5/http/cache/HttpCacheEntry.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/AbstractBinaryAsyncCacheStorage.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/AbstractBinaryCacheStorage.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/ByteArrayCacheEntrySerializer.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/HttpByteArrayCacheEntrySerializer.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/ehcache/EhcacheHttpCacheStorage.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/memcached/MemcachedHttpAsyncCacheStorage.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/memcached/MemcachedHttpCacheStorage.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/HttpTestUtils.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestAbstractSerializingAsyncCacheStorage.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestAbstractSerializingCacheStorage.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestHttpByteArrayCacheEntrySerializer.java

Improve HttpByteArrayCacheEntrySerializer class:
- Add new method to serialize and deserialize cache entries using HTTP response and request objects.
- Improve performance by optimizing buffer size and output stream usage.
- Add escape headers method to escape headers in the HTTP response.
- Add metadata pseudo headers to the HTTP response headers, including storage key, response date, request date, no content, variant map key, and variant map value.

Improve HttpByteArrayCacheEntrySerializer class by adding new methods and enhancing performance.

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/HttpAsyncClientBuilder.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/HttpClientBuilder.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/routing/DistributedProxySelector.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/classic/DistributedProxySelectorTest.java

This pull request adds support for proxy failover in the Apache HttpClient. The current implementation of the ProxySelectorRoutePlanner selects a single proxy from the list returned by the java.net.ProxySelector API. If the client can't open a socket to the proxy, other proxies in the list are ignored and the request fails. This is not optimal in network configurations where proxies can go up and down for maintenance.
To address this, I have implemented a new FailoverProxySelector class that selects a list of proxies for the given URI by delegating to the next available ProxySelector in the list, until a non-empty proxy list is returned. Once a non-empty proxy list is returned, it becomes the active ProxySelector and is used for subsequent calls to select(). The active ProxySelector is …

Add support for proxy failover

---

httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachedHttpResponseGenerator.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestCachingExecChain.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestProtocolRecommendations.java

This commit adds the Last-Modified header to the 304 Not Modified response when the ETag header is not present in the cache entry. This aligns the behavior with the recommendations in RFC 7232 and helps clients that rely on the Last-Modified header for cache updates.

Add Last-Modified header to 304 response when ETag is not present

---

httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/AsyncCachingExec.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachedResponseSuitabilityChecker.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachingExec.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestCachedResponseSuitabilityChecker.java

Add a check in CachedResponseSuitabilityChecker to ensure that cache entries created by HEAD requests are not used to serve GET requests.

Cache entries created by HEAD

---

httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/AsyncCachingExec.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachedResponseSuitabilityChecker.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachingExec.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestCachedResponseSuitabilityChecker.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestCachingExecChain.java

This PR adds handling for 304 Not Modified responses. When a 304 response is received, the cache entry is updated and the updated entry is used to generate the response.
Changes:
- Added code to handle 304 Not Modified responses in `CachingHttpAsyncClient`. and `CachingExec`

Handle 304 Not Modified responses

---

httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/AsyncCachingExec.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CacheControl.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CacheControlHeaderParser.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachingExec.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachingExecBase.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/ResponseCachingPolicy.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/CacheControlParserTest.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestCachingExecChain.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestResponseCachingPolicy.java

This pull request addresses ticket [HTTPCLIENT-2273](https://issues.apache.org/jira/browse/HTTPCLIENT-2273), which identifies an issue with the Apache HttpComponents client's handling of the "no-cache" directive when used with specific header fields, as outlined in RFC 7234.
Changes made to address this issue include:
- Updating the caching module to correctly identify and handle "no-cache" directives with specific header fields. This was done by modifying the `responseContainsNoCacheDirective` method.
-  Modifying the `handleCacheHit` method to ensure that a cached entry is revalidated with the origin server when a "no-cache" directive with specific header fields is present in the response.
- Ensuring that the rest of the response is still cacheable when the specified header fields are …

HTTPCLIENT-2273: Enhance "no-cache" directive handling

---

httpclient5/src/test/java/org/apache/hc/client5/http/impl/classic/TestAIMDBackoffManager.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/classic/TestLinearBackoffManager.java

This PR addresses intermittent test failures observed in the `AIMDBackoffManager` test suite. 
Test methods `backoffDoesNotAdjustDuringCoolDownPeriod`, `probeDoesNotAdjustDuringCooldownPeriod` , `probeDoesNotAdjustDuringCooldownPeriod` and `backoffDoesNotAdjustDuringCoolDownPeriod` previously used `Thread.sleep()` to mimic passage of time. However, this approach proved to be unstable and led to random test failures, largely due to the non-guarantee of precise timing with `Thread.sleep()`.
To mitigate this, we adopted a busy waiting approach using `System.currentTimeMillis()`. In essence, we loop until a specific future time (1 millisecond ahead) is reached. Although this is generally not an ideal solution for production code due to its CPU-intensive nature, it is a reasonable compromise …

Improve Test Robustness and Reliability

---

httpclient5-cache/src/main/java/org/apache/hc/client5/http/cache/CacheHeaderSupport.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/cache/HttpCacheEntry.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CacheUpdateHandler.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CacheValidityPolicy.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachedHttpResponseGenerator.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachedResponseSuitabilityChecker.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/cache/TestCacheHeaderSupport.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/HttpTestUtils.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestCacheUpdateHandler.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestCacheValidityPolicy.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestCachedHttpResponseGenerator.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestCachedResponseSuitabilityChecker.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestProtocolRequirements.java

As per [RFC 9111 3.1](https://datatracker.ietf.org/doc/html/rfc9111#name-storing-header-and-trailer-) the cache now filters out hop-by-hop and connection specific headers prior to committing them to the storage. It also no longer stores the original `Content-Length` which is now gets generated based on the underlying cache entry resource.
@arturobernalg Please review.

HTTPCLIENT-2277: do not store hop-by-hop and connection specific headers in cache

---

httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CacheValidityPolicy.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachedResponseSuitabilityChecker.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachingExecBase.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestCacheValidityPolicy.java

This commit enhances the getFreshnessLifetime() method in the CacheValidityPolicy class to better comply with RFC [9111 4.1](https://datatracker.ietf.org/doc/html/rfc9111#name-calculating-freshness-lifet). The method now accounts for a negative Duration between the Date and Expires header fields.

HTTPCLIENT-2277: Update Freshness Lifetime Calculation (RFC 9111 4.2.1)

---

httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CacheValidityPolicy.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/ResponseCachingPolicy.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestCacheValidityPolicy.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestProtocolRequirements.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestResponseCachingPolicy.java

This commit enhances the processing and calculation of the "Age" response header field to comply fully with Sections 5.1 
and 4.2.3 of RFC9111.
Changes include:
- Parsing of the Age field value as a non-negative integer, representing time in seconds. 
- Handling of messages with list-based Age field values, using the first member and discarding subsequent ones.
- Ignoring of invalid field values (e.g., containing something other than a non-negative integer).
- The presence of an Age header field implies that the response was not generated or validated by the origin server for this request.
- Improved/Fixing the age calculation algorithm considering the apparent age, response delay, corrected age value, and current age to align it with the standard.
-

HTTPCLIENT-2277: Improve Age Header Handling and Calculation in Accordance with RFC9111.

---

httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/BasicHttpAsyncCache.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/BasicHttpCache.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CacheKeyGenerator.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestBasicHttpCache.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestCacheKeyGenerator.java

Presently a lot of cache operations are sub-optimal and redundant. The same cache key may be generated and the same cache lookup performed over and over again in different places in the course of a single request execution
I am optimizing the cache code starting with the most fundamental bit: the cache key generator
Key generator changes:
* improved normalization of variant keys
* potentially less intermediate garbage and a better performance of key computation
@arturobernalg Please review.

HTTPCLIENT-2277: Revision and optimization of cache key generation

---

pom.xml

- Bump Apache Log4j from 2.19.0 to 2.20.0
- Bump Mockito from 4.8.1 to 4.11.0

Bump Log4j and Mockito

---

httpclient5-cache/src/main/java/org/apache/hc/client5/http/cache/HeaderConstants.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/AsyncCachingExec.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/BasicHttpAsyncCache.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/BasicHttpCache.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CacheHit.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CacheInvalidatorBase.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CacheMatch.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CacheableRequestPolicy.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachedHttpResponseGenerator.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachedResponseSuitabilityChecker.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachingExec.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachingExecBase.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/ConditionalRequestBuilder.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/HttpAsyncCache.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/HttpCache.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/RequestProtocolCompliance.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/ResponseCachingPolicy.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/ResponseProtocolCompliance.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/cache/TestHttpCacheEntry.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/ContainsHeaderMatcher.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/HttpTestUtils.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestBasicHttpCache.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestCacheableRequestPolicy.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestCachingExecChain.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestConditionalRequestBuilder.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestProtocolRequirements.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestRequestProtocolCompliance.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestResponseCachingPolicy.java

This is a complete redesign and re-write of the internal cache implementations intended
* to improve internal cache APIs
* to provide support for partial matches (no direct match but there are variants for the same root)
* to eliminate repetitive, redundant cache key calculations
* to eliminate unnecessary duplicate cache look-ups in the course of a single message exchange       
@arturobernalg Please review.

HTTPCLIENT-2277: optimization of internal cache operations

---

httpclient5-cache/src/main/java/org/apache/hc/client5/http/cache/HeaderConstants.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CacheControlHeaderParser.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/ResponseCacheControl.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/ResponseCachingPolicy.java

This commit introduces changes to handle the 'must-understand' directive in accordance with the updated HTTP cache-related RFC 9111. The logic ensures that the cache only stores responses with status codes it understands when the 'must-understand' directive is present.
This implementation adheres to the following RFC guidance:
- A cache that understands and conforms to the requirements of a response's status code may cache it when the 'must-understand' directive is present.
- If the 'no-store' directive is present along with the 'must-understand' directive, the cache can ignore the 'no-store' directive if it understands the status code's caching requirements.

HTTPCLIENT-2277: Implement must-understand directive according to RFC9111

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/auth/DigestScheme.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/auth/TestDigestScheme.java

For digest authentication, in RFC 7616 section "3.4 The Authorization
Header Field":
The values of the opaque and algorithm fields must be those supplied
in the WWW-Authenticate response header field for the entity being
requested.
This commit honors that rule, and removes the previous behavior that
augmented the request header with "algorithm=MD5" when none was provided
in the server's response.
Aside from the specification, it also stands to reason that if the
server failed to provide "algorithm=..." in its "WWW-Authenticate"
header, the server should be fine with the client failing to provide
"algorithm=..." in the "Authorization" header.
The motivation for this change is that including "algorithm=MD5" in the
"Authorization" header causes http requests to fail when made to an
embedded …

Per RFC 7616, use the provided Response algorithm in the Request

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/PoolingHttpClientConnectionManager.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/nio/PoolingAsyncClientConnectionManager.java

At the moment, when i pass validateAfterInactivity as Timeout.ZERO_MILLISECONDS, it has the effect of never validating the connection at all, because that is how Deadline.calculate works. However, the check for TimeValue.isNonNegative for validateAfterInactivity before the deadline check suggests this is not the intended behavior.
Furthermore, we are trying to communicate with a server that always closes a h2 connection after one request. Without a way to force revalidation every time, this runs into issues when a connection is taken from the pool.

Check for timeToLive == 0

---

httpclient5-cache/src/main/java/org/apache/hc/client5/http/cache/HeaderConstants.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CacheControl.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CacheControlHeaderParser.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/RequestCacheControl.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/ResponseCacheControl.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/ResponseCachingPolicy.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/CacheControlParserTest.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestResponseCachingPolicy.java

This commit adds the functionality to handle the 'immutable' directive in the Cache-Control header as per the RFC specifications.
Key changes include:
- The 'immutable' directive is checked in the Cache-Control of an HTTP response, indicating that the origin server will not update the resource representation during the response's freshness lifetime.
- If the 'immutable' directive is present and the response is still fresh, the response is considered cacheable without further validation.
- Ignoring any arguments with the 'immutable' directive, as per RFC stipulations.
- Treating multiple instances of the 'immutable' directive as equivalent to one.

RFC8246  HTTP Immutable Responses

---

httpclient/src/main/java/org/apache/http/impl/conn/DefaultHttpClientConnectionOperator.java
httpclient/src/test/java/org/apache/http/impl/client/integration/TestConnectionManagement.java
httpclient/src/test/java/org/apache/http/impl/conn/TestHttpClientConnectionOperator.java

This change is a partial backport of a change from 5.x, which fixes the issue described in https://issues.apache.org/jira/browse/HTTPCLIENT-2288.

HTTPCLIENT-2288 - Retry logic in DefaultHttpClientConnectionOperator doesn't handle SocketException

---

httpclient5-cache/src/main/java/org/apache/hc/client5/http/cache/HttpCacheEntry.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/cache/HttpCacheEntryFactory.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/AsyncCachingExec.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/BasicHttpAsyncCache.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/BasicHttpCache.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachingExec.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/HttpAsyncCache.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/HttpByteArrayCacheEntrySerializer.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/HttpCache.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/cache/TestHttpCacheEntry.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/cache/TestHttpCacheEntryFactory.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/HttpCacheEntryMatcher.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/HttpTestUtils.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestBasicHttpAsyncCache.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestBasicHttpCache.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestByteArrayCacheEntrySerializer.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestCachingExecChain.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestHttpByteArrayCacheEntrySerializer.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestProtocolRequirements.java

* request URI stored in cache is now normalized and is presently expected to be the same as the root key
* removed references to variant cache keys from the cache entry
* Variants in root entries are now represented as a set, not as a map

HTTPCLIENT-2284: Cache entry representation improvements

---

httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/BasicHttpCacheStorage.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/BasicIdGenerator.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CacheRevalidatorBase.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/ManagedHttpCacheStorage.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/cookie/IgnoreCookieSpecFactory.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/cookie/RFC6265CookieSpecFactory.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/BasicHttpClientConnectionManager.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/PoolingHttpClientConnectionManager.java
httpclient5/src/main/java/org/apache/hc/client5/http/psl/PublicSuffixMatcherLoader.java

- Replaced `synchronized` blocks with `ReentrantLock` in `LeaseRequest` to better support virtual threads introduced in JDK 21.
- Ensured each `LeaseRequest` instance has its own unique lock for maintaining original synchronization semantics.
- Addressed potential performance and deadlock issues with virtual threads by using explicit lock primitives from `java.util.concurrent.locks`.

HTTPCLIENT-2290 - Refactor HttpClient synchronized sections for virtual threads

---

httpclient5/src/main/java/org/apache/hc/client5/http/async/AsyncExecChainHandler.java
httpclient5/src/main/java/org/apache/hc/client5/http/classic/ExecChainHandler.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/AsyncHttpRequestRetryExec.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/HttpRequestRetryExec.java

Document classic and async exec chain behaviour when automatic retries are enabled.
https://issues.apache.org/jira/browse/HTTPCLIENT-2291

Document exec chain behaviour when automatic retries are enabled.

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/ProxyClient.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/classic/TestProxyClient.java

This PR introduces a change to the ProxyClient class to ensure that a port is always specified when making a CONNECT request, in line with the requirements set out in [RFC 9110.](https://www.rfc-editor.org/rfc/rfc9110#name-connect)

HTTPCLIENT-2293 Enforce Port Specification for CONNECT Request

---

httpclient5-cache/src/main/java/org/apache/hc/client5/http/cache/HttpCacheEntryFactory.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/AsyncCachingExec.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/BasicHttpAsyncCache.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/BasicHttpCache.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CacheKeyGenerator.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachingExec.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/HttpAsyncCache.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/HttpCache.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/cache/TestHttpCacheEntryFactory.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/HttpTestUtils.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestBasicHttpAsyncCache.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestBasicHttpCache.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestCacheKeyGenerator.java

Changes:
* improved and simplified internal cache API
* corrected cache update logic after a variant negotiation
* more tests
* fixed regression

HTTPCLIENT-2277: internal cache API and cache update redesign

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/HttpClientBuilder.java
httpclient5/src/main/java/org/apache/hc/client5/http/protocol/RequestIfRange.java
httpclient5/src/test/java/org/apache/hc/client5/http/protocol/TestRequestIfRange.java

This pull request aims to introduce support for the "If-Range" header as specified in RFC 9110. The "If-Range" header provides a more efficient way to handle partial content retrieval and is a crucial step towards full support for Range requests in our HTTP client component.
**Note:** This is the first step towards comprehensive support for HTTP Range Requests in our project.

HTTPCLIENT-2293 - Implement 'If-Range' request validation as per RFC9110

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/HttpClientBuilder.java
httpclient5/src/main/java/org/apache/hc/client5/http/protocol/RequestTraceInterceptor.java
httpclient5/src/test/java/org/apache/hc/client5/http/protocol/TestRequestTraceInterceptor.java

-  Add RequestTraceInterceptor class to handle HTTP TRACE requests in compliance with RFC 7231, Section 4.3.8.
-  Throw ProtocolException for sensitive headers like 'Authorization' and 'Cookie' in TRACE requests.
-  Throw ProtocolException if TRACE request contains a body.

 HTTPCLIENT-2293 - Implement RFC-compliant TRACE request interceptor

---

httpclient5/src/main/java/org/apache/hc/client5/http/ssl/TrustAllStrategy.java
httpclient5/src/main/java/org/apache/hc/client5/http/ssl/TrustSelfSignedStrategy.java

Tries to improve the documentation of `TrustAllStrategy` and `TrustSelfSignedStrategy` by mentioning their security implications and suggesting more secure alternatives.
For `TrustSelfSignedStrategy` it also documents what exactly the strategy does. Otherwise without looking at the implementation details users might erroneously think it is always necessary to use `TrustSelfSignedStrategy` when using self-signed certificates (even if they are also in the truststore), which is not the case.
Any feedback is appreciated!

Add security warning to TrustStrategy implementations documentation

---

httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/AsyncCachingExec.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachingExec.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachingExecBase.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachingH2AsyncClientBuilder.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachingHttpAsyncClientBuilder.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachingHttpClientBuilder.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/RequestViaCache.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/ResponseCacheConformance.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/ResponseCachingPolicy.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/ResponseViaCache.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/ViaCacheGenerator.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestCachingExecChain.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestProtocolRequirements.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestResponseCacheConformance.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestViaCacheGenerator.java

* `ResponseCachingPolicy` optimized to generate less intermediate garbage while paring `Via` headers
* `Via` request and response header generation moved from the caching exec interceptors into separate protocol interceptors

HTTPCLIENT-2293: Via header improvements

---

httpclient5/src/test/java/org/apache/hc/client5/http/examples/AsyncClientCustomSSL.java
httpclient5/src/test/java/org/apache/hc/client5/http/examples/ClientCustomSSL.java

See also discussion in https://issues.apache.org/jira/browse/HTTPCLIENT-2302
This tries to make the user aware that:
- Usage of `TrustStrategy` is optional
- The specific usage in the examples does not prevent man-in-the-middle attacks
Feedback is appreciated!

HTTPCLIENT-2302: Add comment to TrustStrategy usage in examples

---

httpclient5/src/test/java/org/apache/hc/client5/http/impl/classic/TestAIMDBackoffManager.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/classic/TestLinearBackoffManager.java

This enhancement ensures that the tests for 'BackoffManager' run successfully even in resource-constrained environments, making them more resilient and reliable .

Fix features BackoffManager Unit Tests in Resource-Constrained Environments

---

httpclient5/src/test/java/org/apache/hc/client5/http/impl/classic/TestExponentialBackoffManager.java

This PR refactors the unit tests for `ExponentialBackoffManager` to remove the use of Thread.sleep(), making the tests more reliable and faster.

Refactor ExponentialBackoffManager Tests to Remove Thread.sleep().

---

httpclient5/src/main/java/org/apache/hc/client5/http/protocol/RequestIfRange.java

* Updates the RequestIfRange class to utilize DateUtils for parsing standard HTTP dates.
* Optimize time difference check in RequestIfRange with Instant API.

Refactor RequestIfRange class to use DateUtils for date parsing.

---

httpclient5-testing/pom.xml

The slf4j-api is declared without assigning a dependency scope, leading to a default scope compile. But it's only used for testing with classes [org.slf4j.Logger, org.slf4j.LoggerFactory] in file “TypeAsyncResources.java" and "TestClientResources.java".
```
<dependency>
<groupId>org.slf4j</groupId>
<artifactId>slf4j-api</artifactId>
</dependency>
```
This brings redundant compile time dependency for the module, increasing the probability of dependency conflict for downstream users.
Changing the dependency scope to test can help. After changing the dependency scope to "test," I recompiled the module and executed the tests. Following these adjustments, the module compiled successfully, and all the tests passed.

slf4j-api in httpcomponets-testing module is set to a wrong dependency scope.

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/BasicHttpClientConnectionManager.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/io/TestBasicHttpClientConnectionManager.java

The key change involves using the local `conn` variable, obtained from `internalEndpoint`.detach(), to ensure we're acting on the correct connection instance.

HTTPCLIENT-2301. Fix stale connection handling in BasicHttpClientConnectionManager

---

httpclient5-cache/src/main/java/org/apache/hc/client5/http/cache/HttpCacheEntry.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/cache/HttpCacheEntryFactory.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/AsyncCachingExec.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/BasicHttpAsyncCache.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/BasicHttpCache.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CacheControlHeaderParser.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CacheKeyGenerator.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CacheSuitability.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CacheValidityPolicy.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CacheableRequestPolicy.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachedResponseSuitabilityChecker.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachingExec.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/CachingExecBase.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/RequestCacheControl.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/ResponseCacheControl.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/ResponseCachingPolicy.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/cache/TestHttpCacheEntryFactory.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestCacheKeyGenerator.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestCacheValidityPolicy.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestCacheableRequestPolicy.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestCachedResponseSuitabilityChecker.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestCachingExecChain.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestProtocolAllowedBehavior.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestProtocolRequirements.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestResponseCachingPolicy.java

* Aligns the behavior of the caching protocol handlers with the specification requirements (sections 3 and 4 RFC 9111)
* Improved normalization of variant header elements
* Bug fixes

HTTPCLIENT-2277: RFC 9111 conformance improvements / bug fixes

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/AsyncRedirectExec.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/RedirectExec.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/classic/TestRedirectExec.java

This change-set fixes incorrect handling of non-GET requests with a `SEE OTHER`redirect followed by another redirect.

SEE OTHER redirect handling fix

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/auth/BasicScheme.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/auth/TestBasicScheme.java

Introduced a new method, `validatePassword`, in the `BasicScheme` class to enforce password validation in line with RFC 7617 standards. This method includes control character validation for passwords, ensuring they adhere to RFC 7617 by not containing any control characters.

Implement Password Validation in BasicScheme.

---

httpclient5-testing/src/main/java/org/apache/hc/client5/testing/async/AuthenticatingAsyncDecorator.java
httpclient5-testing/src/main/java/org/apache/hc/client5/testing/auth/BasicAuthenticationHandler.java
httpclient5-testing/src/main/java/org/apache/hc/client5/testing/classic/AuthenticatingDecorator.java
httpclient5/src/main/java/org/apache/hc/client5/http/ContextBuilder.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/auth/BasicScheme.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/auth/BasicSchemeFactory.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/auth/TestBasicScheme.java

- Deprecated the constructor in BasicSchemeFactory that allows setting a custom Charset.
- Updated the default constructor to use StandardCharsets.UTF_8, aligning with RFC 7617 which mandates UTF-8 encoding for Basic Authentication.

Enforce UTF-8 Encoding in BasicSchemeFactory for RFC 7617 Compliance

---

httpclient5/src/main/java/org/apache/hc/client5/http/ssl/SSLConnectionSocketFactory.java

Hi,
Just after upgrading to httpclient5 5.2.2, we get the following exception:
```
java.lang.IllegalArgumentException: Invalid Proxy
at java.base/java.net.Socket.<init>(Socket.java:216)
at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.createSocket(SSLConnectionSocketFactory.java:208)
at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:447)
at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:162)
at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:172)
at …
```

Fixes Invalid Proxy exception when using a SSL client without Proxy

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/PoolingHttpClientConnectionManager.java

This commit is to improve debug logging around connections that are not reusable. This [previous commit ](https://github.com/apache/httpcomponents-client/commit/9cfdd54c94ab641a887e43ca1f4ae56beab5cd90) introduced usage of the [isConsistent](https://github.com/apache/httpcomponents-core/blob/d1c77bc7f7697548cd83d04ba87a1ec7105da308/httpcore5/src/main/java/org/apache/hc/core5/http/io/HttpClientConnection.java#L54) variable. 
Upon upgrading from v4.5 -> 5.x I witnessed increased latency between version due to connections being closed and it not being obvious why. I eventually pinpointed to this change, so improving the debug logging around this to hopefully help others in the future.

Improve debug logging around connections that cannot be reused

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/AsyncConnectExec.java

This change-set fixes the problem reported in HTTPCLIENT-2310

 HTTPCLIENT-2310: Async Connect exec handler incorrectly pipes CONNECT requests through the main request protocol chain

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/auth/DigestScheme.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/auth/TestDigestScheme.java

This commit introduces support for the userhash parameter in Digest Authentication, conforming to the specifications outlined in RFC 7616. The userhash parameter enhances security by allowing the client to hash the username before transmission, thereby protecting the username during transport. This implementation ensures that when the server indicates support for username hashing (userhash=true), the client correctly calculates and includes the hashed username in the Authorization header field, adhering to the protocol defined in RFC 7616 for enhanced security in HTTP Digest Access Authentication.

Implement Support for Userhash Parameter in Digest Authentication as per RFC 7616

---

httpclient5/src/main/java/org/apache/hc/client5/http/entity/mime/HttpRFC7578Multipart.java
httpclient5/src/main/java/org/apache/hc/client5/http/entity/mime/MimeConsts.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/auth/DigestScheme.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/auth/RFC5987Codec.java
httpclient5/src/main/java/org/apache/hc/client5/http/utils/CodingException.java
httpclient5/src/test/java/org/apache/hc/client5/http/entity/mime/HttpRFC7578MultipartTest.java
httpclient5/src/test/java/org/apache/hc/client5/http/entity/mime/TestMultipartEntityBuilder.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/auth/RFC5987CodecTest.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/auth/TestDigestScheme.java

Introduces validation and decoding logic for the 'username*' field in the DigestScheme class. The changes ensure compliance with RFC 7616 and RFC 5987 by handling cases where the 'username' contains characters not allowed in an ABNF quoted-string.

Implement username* validation and decoding in DigestScheme

---

httpclient5-fluent/src/main/java/org/apache/hc/client5/http/fluent/ContentResponseHandler.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/fluent/TestFluent.java

Resolved a bug [HTTPCLIENT-2312](https://issues.apache.org/jira/browse/HTTPCLIENT-2312) where the response body was truncated to 256 bytes in all cases, including successful responses.

HTTPCLIENT-2312Fix Response Body Truncation Issue in ContentResponseHandler

---

httpclient5/src/main/java/org/apache/hc/client5/http/SystemDefaultDnsResolver.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/InMemoryDnsResolver.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/DefaultHttpClientConnectionOperator.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/nio/MultihomeIOSessionRequester.java

Make sure an `UnknownHostException` is thrown, even if a custom `DnsResolver` implementation is used.
Fixes the issue of HTTPCLIENT-2314

HTTPCLIENT-2314: Handle gracefully a failure of DnsResolver to return a list of resolved addresses

---

httpclient5/src/main/java/org/apache/hc/client5/http/socket/PlainConnectionSocketFactory.java
httpclient5/src/main/java/org/apache/hc/client5/http/ssl/SSLConnectionSocketFactory.java

In order to allow for backwards-compatibility with projects that override/extend the existing plain and ssl connection factories, we'll specify the createSocket(Proxy, HttpContext) method to call the original createSocket method when proxy is null.

Allow backwards-compatible createSocket calls

---

httpclient5-testing/src/test/java/org/apache/hc/client5/testing/sync/TestClientRequestExecution.java
httpclient5/src/main/java/org/apache/hc/client5/http/EndpointInfo.java
httpclient5/src/main/java/org/apache/hc/client5/http/async/AsyncExecRuntime.java
httpclient5/src/main/java/org/apache/hc/client5/http/classic/ExecRuntime.java
httpclient5/src/main/java/org/apache/hc/client5/http/config/RequestConfig.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/ProtocolSwitchStrategy.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/AsyncConnectExec.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/HttpAsyncClientBuilder.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/HttpAsyncMainClientExec.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/InternalH2AsyncExecRuntime.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/InternalHttpAsyncExecRuntime.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/ConnectExec.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/HttpClientBuilder.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/InternalExecRuntime.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/MainClientExec.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/BasicHttpClientConnectionManager.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/DefaultHttpClientConnectionOperator.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/PoolingHttpClientConnectionManager.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/nio/DefaultAsyncClientConnectionOperator.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/nio/PoolingAsyncClientConnectionManager.java
httpclient5/src/main/java/org/apache/hc/client5/http/io/ConnectionEndpoint.java
httpclient5/src/main/java/org/apache/hc/client5/http/nio/AsyncConnectionEndpoint.java
httpclient5/src/main/java/org/apache/hc/client5/http/protocol/RequestUpgrade.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/TestProtocolSwitchStrategy.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/classic/TestMainClientExec.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/io/TestBasicHttpClientConnectionManager.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/io/TestHttpClientConnectionOperator.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/io/TestPoolingHttpClientConnectionManager.java
httpclient5/src/test/java/org/apache/hc/client5/http/protocol/TestRequestUpgrade.java

This change-set adds support for an optional upgrade to TLS of HTTP/1.1 connections through `Upgrade` / `Switch-Protocol` handshake

HTTPCLIENT-751:  Support for RFC 2817 (Upgrading to TLS Within HTTP/1.1)

---

httpclient5/src/main/java/org/apache/hc/client5/http/HttpRoute.java
httpclient5/src/main/java/org/apache/hc/client5/http/RouteInfo.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/InternalAbstractHttpAsyncClient.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/InternalH2AsyncClient.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/InternalH2AsyncExecRuntime.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/InternalH2ConnPool.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/InternalHttpAsyncClient.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/MinimalH2AsyncClient.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/InternalHttpClient.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/BasicHttpClientConnectionManager.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/DefaultHttpClientConnectionOperator.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/PoolingHttpClientConnectionManager.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/nio/DefaultAsyncClientConnectionOperator.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/nio/PoolingAsyncClientConnectionManager.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/routing/DefaultRoutePlanner.java
httpclient5/src/main/java/org/apache/hc/client5/http/io/HttpClientConnectionOperator.java
httpclient5/src/main/java/org/apache/hc/client5/http/nio/AsyncClientConnectionOperator.java
httpclient5/src/main/java/org/apache/hc/client5/http/routing/HttpRoutePlanner.java
httpclient5/src/test/java/org/apache/hc/client5/http/TestHttpRoute.java
httpclient5/src/test/java/org/apache/hc/client5/http/examples/AsyncClientSNI.java
httpclient5/src/test/java/org/apache/hc/client5/http/examples/ClientSNI.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/classic/TestInternalHttpClient.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/io/TestBasicHttpClientConnectionManager.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/io/TestHttpClientConnectionOperator.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/io/TestPoolingHttpClientConnectionManager.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/routing/TestDefaultRoutePlanner.java

* Connection route info now request URI authority
* The default route planner and connections managers now take request URI authority when calculating the connection route and when pooling and re-using connections

SNI support improvements

---

httpclient5-testing/src/test/java/org/apache/hc/client5/testing/sync/TestDefaultClientTlsStrategy.java
httpclient5/src/main/java/org/apache/hc/client5/http/ssl/AbstractClientTlsStrategy.java
httpclient5/src/main/java/org/apache/hc/client5/http/ssl/ClientTlsStrategyBuilder.java
httpclient5/src/main/java/org/apache/hc/client5/http/ssl/ConscryptClientTlsStrategy.java
httpclient5/src/main/java/org/apache/hc/client5/http/ssl/DefaultClientTlsStrategy.java
httpclient5/src/main/java/org/apache/hc/client5/http/ssl/HostnameVerificationPolicy.java

This change-set extends the public APIs with hostname verification options:
* `Built-In`: Hostname verification is delegated to the JSSE provider, usually executed during the TLS handshake 
* `Client`: Hostname verification is executed by HttpClient post TLS handshake
* `Both`: Hostname verification is executed by the JSSE provider and by HttpClient post TLS handshake
The `Both` option is used by default. It provides the benefit of backward compatibility with the behavior of previous versions of HttpClient, added security (hostnames get verified by the JSSE provider and by the client) and fail-early approach (invalid hostnames can get rejected during the TLS handshake). At the same some checks may get performed twice and result in certain (likely minor) performance hit. In the future …

HTTPCLIENT-2151: Support for JSSE in-built endpoint identification

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/BasicHttpClientConnectionManager.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/PoolingHttpClientConnectionManager.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/nio/PoolingAsyncClientConnectionManager.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/io/TestPoolingHttpClientConnectionManager.java

This PR addresses the issue described in [HTTPCLIENT-2318](https://issues.apache.org/jira/browse/HTTPCLIENT-2318) by enhancing the `PoolingHttpClientConnectionManager`. It introduces an isShutdown method for clear state checking and refines the close method for improved resource management, aiming to improve usability and reliability without affecting backward compatibility.

HTTPCLIENT-2318 - Enhance PoolingHttpClientConnectionManager with isShutdown State Check.

---

httpclient5/src/main/java/org/apache/hc/client5/http/utils/DateUtils.java
httpclient5/src/test/java/org/apache/hc/client5/http/utils/TestDateUtils.java

This PR provides a fix for [HTTPCLIENT-2319](https://issues.apache.org/jira/browse/HTTPCLIENT-2319), where parsing unzoned timestamp strings using `parseDate` resulted in a `DateTimeException` due to the absence of timezone information.

Resolve DateTimeException for Unzoned Timestamps in parseDate

---

httpclient5/src/main/java/org/apache/hc/client5/http/entity/mime/MultipartEntityBuilder.java
httpclient5/src/test/java/org/apache/hc/client5/http/entity/mime/TestMultipartEntityBuilder.java
httpclient5/src/test/java/org/apache/hc/client5/http/entity/mime/TestMultipartFormHttpEntity.java

See https://issues.apache.org/jira/browse/HTTPCLIENT-2325
This PR does not modify `ContentType.MULTIPART_FORM_DATA`, and it might have backward compatibility side-effects that I do not want touching in this PR.

HTTPCLIENT-2325 Avoid adding "; charset=" for multipart/form-data requests

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/DefaultHttpClientConnectionOperator.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/PoolingHttpClientConnectionManager.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/PoolingHttpClientConnectionManagerBuilder.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/nio/DefaultAsyncClientConnectionOperator.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/nio/PoolingAsyncClientConnectionManager.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/nio/PoolingAsyncClientConnectionManagerBuilder.java

As discussed on the mailing list, implements a callback for Connection initialization steps.
Useful for collection of metrics on how long each step takes for network troubleshooting.

Callbacks for Connection initialization

---

httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/memcached/MemcachedHttpAsyncCacheStorage.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/memcached/MemcachedHttpCacheStorage.java
httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/memcached/MemcachedOperationCancellationException.java

fixes https://issues.apache.org/jira/browse/HTTPCLIENT-2327

HTTPCLIENT-2327: Propagate CancellationExceptions from MemcachedClient operations as ResourceIOExceptions

---

httpclient5/src/main/java/org/apache/hc/client5/http/protocol/RequestAddCookies.java
httpclient5/src/test/java/org/apache/hc/client5/http/protocol/TestRequestAddCookies.java

Fix for [HTTPCLIENT-2331:](https://issues.apache.org/jira/browse/HTTPCLIENT-2331) Single Cookie Header for Multiple Cookies
When an explicit Cookie header is added using `setHeader()` and multiple cookies exist in the `BasicCookieStore`, `HttpClient` was sending separate Cookie headers for the manually set cookies and the cookies in the store. This fix ensures that if a Cookie header is already present in the request, `HttpClient` skips adding additional Cookie headers from the `BasicCookieStore`. 
This change conforms to the expectation that a single Cookie header should be sent where all cookies are separated by a semicolon, as per [RFC6265](https://www.rfc-editor.org/rfc/rfc6265).

Fix HTTPCLIENT-2331: Skip cookie header generation if a Cookie header is present

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/LaxRedirectStrategy.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/TestLaxRedirectStrategy.java

This commit adds a new implementation of the LaxRedirectStrategy, bringing back functionality similar to that found in HttpClient 4.x. The LaxRedirectStrategy automatically redirects all HEAD, GET, POST, and DELETE requests, relaxing the restrictions imposed by the HTTP specification on automatic redirection of POST methods.
- **Supported Methods**: Redirects HEAD, GET, POST, and DELETE methods.
- **Location Resolution**: Automatically resolves relative redirect URIs against the request URI.
- **Compatibility**: Ensures compatibility with existing 4.x applications by providing a familiar API and redirect behavior.
- **Normalization**: Normalizes and converts the host part of the redirect URI to lowercase, maintaining consistent behavior.
- Simplifies migration from HttpClient 4.x to 5.x …

feat: Reintroduce LaxRedirectStrategy in HttpClient 5.4 for Enhanced Redirect Handling

---

httpclient5/src/main/java/org/apache/hc/client5/http/entity/LazyDecompressingInputStream.java
httpclient5/src/test/java/org/apache/hc/client5/http/entity/TestDecompressingEntity.java

Input streams returned by DecompressingEntity.getContent() should support mark(int) and reset() if the underlying stream does
- Pass calls to the underlying InputStream for mark(int)
- Pass calls to the underlying InputStream for reset()
- LazyDecompressingInputStream extends FilterInputStream
- Reimplement internals fluently
- Reuse Closer.close(Closeable)
- Tested locally with git master 5.3-beta2-SNAPSHOT

Input streams returned by DecompressingEntity.getContent() should support mark(int) and reset()

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/LoggingInputStream.java

- No need to track delegate, it's in super and it's also called `in`
- Constructor shouldn't be public since the class is package-private
- Normalize message in `available()` to match other methods
- Inherit mark/reset behavior which we don't use anyway
- `skip()` uses `in` like other methods for consistency

Reimplement LoggingInputStream as a FilterInputStream

---

httpclient5/src/main/java/org/apache/hc/client5/http/entity/DeflateInputStream.java

Let `DeflateInputStream` extends `FilterInputStream`
- Reduces boilerplate
- Improve Javadoc
- Internal static class can be private
- Reuse constant Deflater.DEFLATED

DeflateInputStream extends FilterInputStream

---

NOTICE.txt
httpclient5/pom.xml
httpclient5/src/main/java/org/apache/hc/client5/http/psl/PublicSuffixMatcherLoader.java
httpclient5/src/main/resources/org/publicsuffix/list/effective_tld_names.dat
httpclient5/src/main/resources/org/publicsuffix/list/readme.txt
httpclient5/src/test/java/org/apache/hc/client5/http/psl/TestPublicSuffixMatcher.java
httpclient5/src/test/java/org/apache/hc/client5/http/psl/TestPublicSuffixMatcherLoader.java

Includes a copy of in https://publicsuffix.org/list/effective_tld_names.dat in `httpclient5/src/test/resources/org/publicsuffix/list/effective_tld_names.dat`
Or, should this be a runtime resource?

Includes a copy of publicsuffix.org's effective_tld_names.dat as a test fixture

---

httpclient/src/main/java/org/apache/http/impl/auth/NTLMEngineImpl.java

Without this flag actual code will be using NTLMv2Session response instead of NTLMv2 response.

Fix NTLMv2 auth problems for AD 2012 and above

---

httpclient5/src/main/java/org/apache/hc/client5/http/ssl/AbstractClientTlsStrategy.java
httpclient5/src/test/java/org/apache/hc/client5/http/ssl/AbstractClientTlsStrategyTest.java

This PR addresses [HTTPCLIENT-2337](https://issues.apache.org/jira/browse/HTTPCLIENT-2337), which involves potentially unsafe logging of `X500Principal` in `SSLConnectionSocketFactory.` The issue is caused by control characters in the `X500Principal` being logged without sanitization, which could interfere with log readability.

HTTPCLIENT-2337: Sanitize X500Principal Logging in ClientTlsStrategy classes

---

httpclient5/src/main/java/org/apache/hc/client5/http/ssl/ClientTlsStrategyBuilder.java

Currently, it is impossible to add  `setHostnameVerificationPolicy` to a call chain

Return builder from setHostnameVerificationPolicy

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/auth/DigestScheme.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/auth/TestDigestScheme.java

Updated the Digest authentication implementation to ensure compliance with RFC requirements for mutual authentication. Specifically, added support for rspauth.

Add  `rspauth` in Digest authentication.

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/auth/DigestScheme.java
httpclient5/src/main/java/org/apache/hc/client5/http/protocol/HttpClientContext.java
httpclient5/src/main/java/org/apache/hc/client5/http/protocol/NextNonceInterceptor.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/auth/TestDigestScheme.java
httpclient5/src/test/java/org/apache/hc/client5/http/protocol/TestNextNonceInterceptor.java

This PR introduces the `NextNonceInterceptor` to process HTTP responses with Authentication-Info headers by extracting the `nextnonce` parameter, as specified in [RFC 7616](https://www.rfc-editor.org/rfc/rfc7616#page-14). The interceptor checks for the presence of this header, retrieves the `nextnonce` value if available, and stores it within the `HttpContext` under the attribute `auth-nextnonce.` This mechanism supports secure client authentication workflows by allowing continuity in nonce-based authentication challenges.

Add NextNonceInterceptor for nextnonce extraction from Authentication-Info headers

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/auth/DigestScheme.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/auth/TestDigestScheme.java

This PR upgrades the DigestScheme implementation to align with RFC 7616 requirements, introducing support for SHA-256 and SHA-512/256 hash algorithms in addition to MD5

Enhance DigestScheme for RFC 7616 Compliance and Expanded Hash Algorithm Support

---

httpclient5/src/main/java/org/apache/hc/client5/http/DnsResolver.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/DefaultHttpClientConnectionOperator.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/nio/MultihomeIOSessionRequester.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/io/TestBasicHttpClientConnectionManager.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/io/TestHttpClientConnectionOperator.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/io/TestPoolingHttpClientConnectionManager.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/nio/MultihomeIOSessionRequesterTest.java

This PR introduces an enhancement to `DefaultHttpClientConnectionOperator`, adding the ability to disable DNS resolution for specific connections. This is particularly useful when connecting to .onion addresses through a SOCKS proxy, where public DNS lookups are not possible or desirable.

HTTPCLIENT-2350 - Enhance HttpClientConnectionOperator with Optional DNS Resolution Control

---

httpclient5-testing/src/test/java/org/apache/hc/client5/testing/async/HttpIntegrationTests.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/async/TestHttpAsyncRequestMultiplexing.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/compatibility/async/HttpAsyncClientCompatibilityTest.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/extension/async/H2OnlyMinimalTestClientBuilder.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/extension/async/H2OnlyTestClientBuilder.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/extension/async/HttpAsyncClientResource.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/extension/async/MinimalTestClientBuilder.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/extension/async/StandardTestClientBuilder.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/extension/async/TestAsyncClientBuilder.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/nio/H2SharingConnPool.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/nio/PoolingAsyncClientConnectionManager.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/nio/PoolingAsyncClientConnectionManagerBuilder.java
httpclient5/src/test/java/org/apache/hc/client5/http/examples/AsyncClientH2FullDuplexExchange.java
httpclient5/src/test/java/org/apache/hc/client5/http/examples/AsyncClientH2Multiplexing.java
httpclient5/src/test/java/org/apache/hc/client5/http/examples/AsyncClientH2ServerPush.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/nio/H2SharingConnPoolTest.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/nio/H2SharingPerRoutePoolTest.java

Experimental connections pool implementation that acts as a caching facade in front of a standard ManagedConnPool and shares already leased connections to multiplex message exchanges over active HTTP/2 connections.

Message multiplexing for the standard async HttpClient

---

httpclient5/src/test/java/org/apache/hc/client5/http/examples/ClientConfiguration.java

This was forgotten in commit: [04594b97a9e61931d3af6847b8f8335f0f91c460](https://github.com/apache/httpcomponents-client/commit/04594b97a9e61931d3af6847b8f8335f0f91c460#diff-f16a6b22809dbe3a415d34c12d4e04b91f136e38334a76e51309a1be4c214bbcR123)

fix(examples): Typo in ClientConfiguration example

---

httpclient5/src/main/java/org/apache/hc/client5/http/ssl/DefaultHostnameVerifier.java
httpclient5/src/test/java/org/apache/hc/client5/http/ssl/TestDefaultHostnameVerifier.java

Normalize Unicode and punycode strings before comparing host and certificate identities. This approach ensures domains like поиск-слов.рф properly match their punycode equivalents.

HTTPCLIENT-2353: Fix IDN hostname mismatch by normalizing host and identity with IDN

---

httpclient5-cache/src/main/java/org/apache/hc/client5/http/impl/cache/ResponseCachingPolicy.java
httpclient5-cache/src/test/java/org/apache/hc/client5/http/impl/cache/TestResponseCachingPolicy.java

Fix HTTPCLIENT-2354 by updating `ResponseCachingPolicy` to handle caching of responses with `must-revalidate, max-age=0` in shared caches. Updated `isExplicitlyCacheable` to account for `must-revalidate` when `max-age=0`, ensuring compliance with RFC 9111. Adjusted isResponseCacheable to permit caching of responses containing Authorization headers if `must-revalidate, s-maxage`, or public directives are present. Enhanced debug logging to reflect caching decisions. Added unit tests to verify that responses with `must-revalidate` and max-age=0 are cacheable in shared caches even with Authorization headers. This fix resolves the issue preventing compliant caching and aligns HttpClient behavior with RFC 9111 specifications.

Fix HTTPCLIENT-2354: Allow caching of responses with "must-revalidate, max-age=0" in shared caches

---

httpclient5/src/main/java/org/apache/hc/client5/http/ssl/DefaultHostnameVerifier.java
httpclient5/src/test/java/org/apache/hc/client5/http/ssl/TestDefaultHostnameVerifier.java

This implementation adds decoding for Subject Alternative Names in X.509 certificates, including:
- DNS names handled as plain text.
- IP addresses decoded from binary (IPv4 and IPv6 supported).
- Fallback to hexadecimal encoding for non-standard or unknown types.

Decode Subject Alternative Names (SAN) for X.509 Certificates

---

httpclient5-testing/src/test/java/org/apache/hc/client5/testing/async/AbstractClassicOverAsyncIntegrationTestBase.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/async/ClassicOverAsyncIntegrationTests.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/async/TestClassicOverAsync.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/async/TestClassicOverAsyncHttp1.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/HttpAsyncClients.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/InternalAbstractHttpAsyncClient.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/CloseableDelegate.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/CloseableHttpResponse.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/MainClientExec.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/MinimalHttpClient.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/compat/AbstractSharedBuffer.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/compat/ClassicToAsyncAdaptor.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/compat/ClassicToAsyncRequestProducer.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/compat/ClassicToAsyncResponseConsumer.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/compat/ClassicToAsyncSupport.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/compat/IOCallback.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/compat/ProtocolException.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/compat/SharedInputBuffer.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/compat/SharedOutputBuffer.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/compat/TransportException.java
httpclient5/src/test/java/org/apache/hc/client5/http/examples/ClientClassicOverAsync.java

Classic APIs over async transport

---

httpclient5-fluent/src/main/java/org/apache/hc/client5/http/fluent/Executor.java
httpclient5-fluent/src/main/java/org/apache/hc/client5/http/fluent/Request.java

@arturobernalg Please review
This change-set adds support for async client as a backend for the Fluent Facade and enables its users to make use of HTTP/2 transport

Async client can now be used internally by the Fluent facade

---

httpclient5/src/main/java/org/apache/hc/client5/http/entity/mime/FormBodyPartBuilder.java
httpclient5/src/main/java/org/apache/hc/client5/http/entity/mime/HttpRFC7578Multipart.java
httpclient5/src/main/java/org/apache/hc/client5/http/entity/mime/MultipartEntityBuilder.java
httpclient5/src/test/java/org/apache/hc/client5/http/entity/mime/TestMultipartForm.java

Implements RFC 6266/5987 filename encoding in multipart/form-data. Adds mode-aware support in FormBodyPartBuilder and HttpRFC7578Multipart, propagates mode via MultipartEntityBuilder, and updates tests. Resolves https://issues.apache.org/jira/browse/HTTPCLIENT-2360.

Enhance filename encoding in multipart/form-data (HTTPCLIENT-2360)

---

httpclient5/src/main/java/org/apache/hc/client5/http/psl/PublicSuffixMatcherLoader.java
httpclient5/src/test/java/org/apache/hc/client5/http/psl/TestPublicSuffixMatcher.java
httpclient5/src/test/java/org/apache/hc/client5/http/psl/TestPublicSuffixMatcherLoader.java

The code of `getDefault` reads like it's supposed to load the entries from `PUBLIC_SUFFIX_LIST` by default, but it doesn't actually work that way in practice. I think this is a bug. This works correctly on 4.x, but the list there already starts with a leading slash:
https://github.com/apache/httpcomponents-client/blob/54900db4653d7f207477e6ee40135b88e9bcf832/httpclient/src/main/java/org/apache/http/conn/util/PublicSuffixMatcherLoader.java#L86
This was sneaking past the tests, because the test for getDefault only checks that it isn't `null`, but a non-null nearly empty default PublicSuffixMatcher is still provided in the case of the url not existing, and the tests for PublicSuffixMatcher themselves reimplement the default loading logic (correctly, since they rely on …

Fix PublicSuffixMatcherLoader#getDefault

---

httpclient5-testing/src/test/java/org/apache/hc/client5/testing/async/AbstractHttpAsyncRedirectsTest.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/sync/TestRedirects.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/DefaultRedirectStrategy.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/AsyncRedirectExec.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/RedirectExec.java
httpclient5/src/main/java/org/apache/hc/client5/http/protocol/RedirectStrategy.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/TestDefaultRedirectStrategy.java

@arturobernalg Please review and double-check.

Disallow automatic request redirection if the original request contains potentially sensitive headers

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/cookie/PublicSuffixDomainFilter.java
httpclient5/src/main/java/org/apache/hc/client5/http/psl/PublicSuffixMatcher.java
httpclient5/src/main/java/org/apache/hc/client5/http/ssl/DefaultHostnameVerifier.java
httpclient5/src/test/java/org/apache/hc/client5/http/psl/TestPublicSuffixMatcher.java
httpclient5/src/test/java/org/apache/hc/client5/http/ssl/TestDefaultHostnameVerifier.java
httpclient5/src/test/resources/suffixlistmatcher.txt

What a bloody mess has been done to `PublicSuffixMatcher` in 5.4!
This change-set corrects the immediate problem with handling of the private domains.
@arturobernalg  Please double-check.

HTTPCLIENT-2365, regression: corrected handling of private domains by PublicSuffixMatcher

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/RequestEntityProxy.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/classic/RequestEntityProxyTest.java

This PR fixes an issue with the `isRepeatable` method in `RequestEntityProxy`. Previously, if the underlying entity was non-repeatable, the proxy would incorrectly return false even before consumption. The fix ensures that the proxy is always considered repeatable until it is consumed, regardless of the underlying entity's repeatability. Tests have been updated to validate this behavior.

HTTPCLIENT-2366 - Fix isRepeatable method in RequestEntityProxy to return true before consumption.

---

httpclient5/src/main/java/org/apache/hc/client5/http/psl/PublicSuffixMatcher.java
httpclient5/src/main/java/org/apache/hc/client5/http/ssl/DefaultHostnameVerifier.java
httpclient5/src/main/java/org/apache/hc/client5/http/utils/DnsUtils.java
httpclient5/src/test/java/org/apache/hc/client5/http/ssl/TestDefaultHostnameVerifier.java

Presently DNS normalization is performed inconsistently and often multiple times over the same input
This change-set 
1. Optimizes DNS normalization and ensures it is performed once per API call
2. Ensures DNS hames / identities always get represented in Unicode
@arturobernalg Please review.

DNS host / identity normalization should be performed only once per public API call

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/ProtocolSwitchStrategy.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/TestProtocolSwitchStrategy.java

refines the ProtocolSwitchStrategy class to improve the parsing of protocol tokens in the Upgrade header, making the implementation more elegant and future-proof.

Enhance ProtocolSwitchStrategy with Simplified Protocol Parsing

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/InternalAbstractHttpAsyncClient.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/InternalHttpClient.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/classic/TestInternalHttpClient.java

Resolves a `NullPointerException` in `InternalAbstractHttpAsyncClient` by adding a null check for resolvedTarget when RoutingSupport.determineHost returns null. Throws `IllegalStateException` for invalid requests, ensuring robust error handling. Addresses [HTTPCLIENT-2367.](https://issues.apache.org/jira/browse/HTTPCLIENT-2367)

Fix NPE in InternalAbstractHttpAsyncClient by adding null check for resolvedTarget

---

httpclient5/src/test/java/org/apache/hc/client5/http/examples/ClientAbortMethod.java
run-example.sh

This commit adds a simple shell script that runs our example programs. I've also fixed a bug in `ClientAbortMethod` that prevents the JVM from shutting down.

Add helper script to run example programs

---

httpclient5-testing/pom.xml
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/extension/sync/StandardTestClientBuilder.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/extension/sync/TestClientBuilder.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/extension/sync/TestClientResources.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/extension/sync/TestServer.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/extension/sync/UnixDomainProxyServer.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/sync/AbstractIntegrationTestBase.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/sync/TestConnectionReuse.java
httpclient5/pom.xml
httpclient5/src/main/java/org/apache/hc/client5/http/HttpRoute.java
httpclient5/src/main/java/org/apache/hc/client5/http/RouteInfo.java
httpclient5/src/main/java/org/apache/hc/client5/http/RouteTracker.java
httpclient5/src/main/java/org/apache/hc/client5/http/config/RequestConfig.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/DefaultHttpClientConnectionOperator.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/PoolingHttpClientConnectionManager.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/nio/DefaultAsyncClientConnectionOperator.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/nio/PoolingAsyncClientConnectionManager.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/routing/DefaultRoutePlanner.java
httpclient5/src/main/java/org/apache/hc/client5/http/io/HttpClientConnectionOperator.java
httpclient5/src/main/java/org/apache/hc/client5/http/nio/AsyncClientConnectionOperator.java
httpclient5/src/main/java/org/apache/hc/client5/http/socket/UnixDomainSocketFactory.java
httpclient5/src/test/java/org/apache/hc/client5/http/TestHttpRoute.java
httpclient5/src/test/java/org/apache/hc/client5/http/examples/UnixDomainSocket.java
httpclient5/src/test/java/org/apache/hc/client5/http/examples/UnixDomainSocketAsync.java
pom.xml

This change adds Unix domain socket support. The sync client uses JUnixSocket, which provides synchronous UDS support through the legacy `java.net.Socket` API; the async client uses the JEP 380 implementation of UDS through the `java.nio.channels.SocketChannel` API (requires JDK16 or later).
Since the synchronous client is tightly coupled to the `Socket` API, we can't trivially use JEP 380 UDS support. We would first have to write an adapter to implement the `Socket` API, backed by a JEP 380 UDS `SocketChannel`. This would require us to implement features like socket option configuration, connection timeouts, and socket timeouts; we would also have to implement APIs like `getInetAddress()` which don't actually make sense in a UDS context. This is probably doable (JUnixSocket does it, …

Add Unix domain socket support

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/H2AsyncClientBuilder.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/HttpAsyncClientBuilder.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/HttpClientBuilder.java
httpclient5/src/test/java/org/apache/hc/client5/http/examples/PublicSuffixLoaderBenchmark.java

The HTTP client builders always construct a client with a non-null cookie spec registry; if a custom instance is not specified, then the builders will use `CookieSpecSupport.createDefault()`, which loads the full public suffix list. The PSL rules are stored on the heap as a `ConcurrentHashMap`, i.e. a giant array (16,384 on my machine) containing map entries, each of which is also allocated as a separate object on the heap. This is a considerable number of live objects that the garbage collector may need to trace. I ran a simple microbenchmark to show the effects of loading the PSL on garbage collection (these numbers are from JDK 1.8):
GC took 2 ms
GC took 2 ms
GC took 2 ms
Loading public suffix list... done (took 193 ms)
GC took 11 ms
GC took 8 ms
GC took 7 ms
This is potentially a …

Omit cookie spec registry when cookie management is disabled

---

httpclient5-testing/src/test/java/org/apache/hc/client5/testing/async/TestAsyncTlsHandshakeTimeout.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/sync/TestTlsHandshakeTimeout.java
httpclient5-testing/src/test/java/org/apache/hc/client5/testing/tls/TlsHandshakeTimeoutServer.java

This change adds basic integration test coverage for TLS handshake timeouts for the sync and async clients. The tests make use of a special test server that times out a single TLS connection attempt and can be configured to time out at two different points in the TLS 4-way handshake.
Note that the TLS handshake timeout, as currently implemented, works like a socket timeout for the TLS handshake phase of the connection: it only limits the amount of time that will be spent on each individual socket read/write operations, not the total time spent in the handshake attempt. The timeout server, for example, could inject a delay before sending the Server Hello, which would cause the client to spend up to double the configured timeout attempting to complete the handshake. There is no test …

Add integration tests for TLS handshake timeouts

---

httpclient5-testing/src/test/java/org/apache/hc/client5/testing/sync/TestSocketTimeout.java

These test cases are intermittently failing in the build environment on macos-latest using JDK11, because some of the calls seem to be taking slightly more than twice as long as they ought to before timing out. I'm not able to reproduce the issue, but it's safe to increase the upper bound: we'll still know if one of the socket timeout config options stops working, since the `assertThrows` assertion will fail.

TestSocketTimeout: Increase upper bound assertion for actual delay

---

httpclient5-testing/src/test/java/org/apache/hc/client5/testing/TestValidateAfterInactivity.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/nio/PoolingAsyncClientConnectionManager.java

`validateAfterInactivity` is primarily a synchronous client feature, since it is necessary to attempt to read from the underlying socket in order to discover that the connection has been closed by the remote peer. The async client doesn't have this issue; the IOReactor is automatically notified when connections are closed and removes them from the pool (see `SingleCoreIOReactor::processClosedSessions`).
For some reason, however, the async client's connection manager treats `validateAfterInactivity` as a kind of connection TTL: if the connection has been idle longer than the `validateAfterInactivity` config value, then the connection is closed immediately unless it is an HTTP/2 connection, in which case a PING frame is used to check for liveness. Since stale connections are removed from …

Fix `validateAfterInactivity` on the async client

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/nio/H2SharingConnPool.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/nio/H2SharingConnPoolTest.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/nio/H2SharingPerRoutePoolTest.java

Return early in H2SharingConnPool#release when the entry’s lease count is zero, so duplicate releases become no-ops and the underlying pool no longer throws `IllegalStateException`.
tested with https://github.com/yhzdys/httpcomponents-client/commit/c8256b33c3adb45cfa2a49efb2dacfb611da9ac1

HTTPCLIENT-2379 - Handle duplicate release() safely in H2SharingConnPool

---

httpclient5/src/main/java/org/apache/hc/client5/http/entity/InputStreamFactory.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/HttpClientBuilder.java

@arturobernalg I realized you should not have deprecated `InputStreamFactory`. It was still perfectly useful at the HttpClientBuilder level for plugging in custom decoders.
How about this change-set?

Undeprecate InputStreamFactory and restore contentDecoderMap functionality in HttpClientBuilder

---

httpclient5/src/main/java/org/apache/hc/client5/http/config/ExpectContinueTrigger.java
httpclient5/src/main/java/org/apache/hc/client5/http/config/RequestConfig.java
httpclient5/src/main/java/org/apache/hc/client5/http/protocol/RequestExpectContinue.java
httpclient5/src/test/java/org/apache/hc/client5/http/protocol/TestRequestExpectContinue.java

This change introduces an opt-in strategy that limits automatic emission of the Expect: 100-continue header to requests executed over a reused (pooled) connection.
It eliminates “No response from server” ambiguity on non-idempotent requests without imposing the extra RTT on brand-new sockets.
Key points
ExpectContinueTrigger enum – two modes: ALWAYS (default, preserves 5.x behaviour) and IF_REUSED.
RequestConfig extension – new field, getter, and builder setter setExpectContinueTrigger(...).
RequestExpectContinue interceptor – now consults the trigger and skips the header when the connection’s EndpointDetails#getRequestCount() is 0.
No binary incompatibility; existing code continues to operate exactly as before.
Unit tests added for both trigger modes.
The behaviour requested in Jira …

HTTPCLIENT-1482: expect-continue only on reused connections

---

httpclient5/src/main/java/org/apache/hc/client5/http/entity/compress/DecompressingEntity.java

@arturobernalg I overlooked the problem with `Content-Encoding` property value returned by DecompressingEntity, Please double-check.

Bug-fix: Corrected DecompressingEntity to return null Content-Encoding (no encoding)

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/ContentCompressionAsyncExec.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/ContentCompressionExec.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/HttpClientBuilder.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/classic/TestContentCompressionExec.java

Treat unsupported content encoding as an error. @arturobernalg Please double-check

Unsupported content encoding to be treated as an error

---

httpclient5-testing/src/test/java/org/apache/hc/client5/testing/sync/TestTlsHandshakeTimeout.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/DefaultHttpClientConnectionOperator.java
pom.xml

This change sets the new KeepAlive-related options directly through the JDK, instead of going through `SocketSupport`. There are two reasons for this.
First, the `SocketSupport` code path doesn't work on Java 8, as it attempts to reflectively call `Socket.setOption()`, which was added in newer versions.
Second, the options themselves _do_ exist on Java 8. The Java socket options were backported to Java 8 in 8u261 (July 2020):
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8194298
As for Windows, it supports `TCP_KEEPIDLE` and `TCP_KEEPINTVL` since Windows 10 version 1709 (October 2017):
https://learn.microsoft.com/en-us/windows/win32/winsock/ipproto-tcp-socket-options
I think it's safe at this point to simply use these features like any other socket option. Unfortunately, it doesn't …

Enable new TcpKeepAlive options on Java 8

---

httpclient5/src/main/java/org/apache/hc/client5/http/async/methods/DeflatingGzipEntityProducer.java
httpclient5/src/main/java/org/apache/hc/client5/http/async/methods/InflatingGzipDataConsumer.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/ContentCompressionAsyncExec.java
httpclient5/src/test/java/org/apache/hc/client5/http/async/methods/GzipRoundTripTest.java
httpclient5/src/test/java/org/apache/hc/client5/http/examples/AsyncClientGzipCompressionExample.java
httpclient5/src/test/java/org/apache/hc/client5/http/examples/AsyncClientGzipDecompressionExample.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/async/TestContentCompressionAsyncExec.java

Adds `InflatingGzipDataConsumer,` `DeflatingGzipEntityProducer` and example/tests so the async client automatically advertises gzip,  inflates gzip/ responses on the fly and streams request bodies through gzip when wrapped. No buffering, CRC + ISIZE trailer written little-endian,

Transparent async content (de)compression with gzip

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/ContentCodingSupport.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/async/ContentCompressionAsyncExec.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/ContentCompressionExec.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/ContentCodingSupportTest.java

Relatively minor code optimization that improves consistency of automatic content decompression by the classic and async transports. @arturobernalg Please double-check.

Content coding support

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/PoolingHttpClientConnectionManager.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/nio/PoolingAsyncClientConnectionManager.java

There was a [report](https://lists.apache.org/thread/ll2q7kh0jtffq8j95v5w17w2zty7g6yb) on the dev list recently about clients getting stuck trying to close out a TLS connection while holding a lock on the connection pool, effectively rendering those clients completely disabled. I thought it should not never happen and it turned out I was wrong. The issue was known and got fixed in `core` but the fix never got applied to `client`.
Basically this change-set makes sure the socket timeout is set to 1 second before connections get closed out inside the pool lock.
@arturobernalg  Please double-check.

Bug fix: Use 1 second timeout when closing out connections inside a connection pool lock

---

httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/OffLockDisposalCallback.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/PoolingHttpClientConnectionManager.java
httpclient5/src/main/java/org/apache/hc/client5/http/impl/io/PoolingHttpClientConnectionManagerBuilder.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/io/NoopOperator.java
httpclient5/src/test/java/org/apache/hc/client5/http/impl/io/TestPoolingHttpClientConnectionManagerOffLockDisposal.java

Close sockets off the pool lock via an async disposer. Improves lease latency under eviction/state mismatch with slow close.Includes classic/async tests and default-disposer baseline.

Pooling managers: offload connection disposal from the pool lock.
